### PR TITLE
refactor(global): updated Bengali Translation

### PR DESCRIPTION
**Pull request by imadill**

### CODE REVIEW

**Comment by amitojsingh366** [comment]
please use proper commit messages *(`yarn commit` or `yarn commit:signed`)*

**Comment by amitojsingh366** [comment]
also 7 commits for two insertions??

**Comment by imadill** [comment]
> also 7 commits for two insertions??

Lol, I dont even know why are the commits from the past 2-3 days are adding up here when I did PRs at that time

**Comment by imadill** [comment]
> please use proper commit messages *(`yarn commit` or `yarn commit:signed`)*
> 

I used `yarn commit` tho, should it be something else than refactor?

**Comment by imadill** [comment]
The git commits aren't clean Ikr, I'll fix some stuff and then do pr

**Pull request closed without merging**
