### PR TITLE
add bot badge (fully baked)

### PR DESCRIPTION
**Pull request by amitojsingh366**
- adds bot badge support to kibbeh
- adds bot badge support to kebab
- adds bot badge support to kousa *(user schema now contains `botOwnerId`)*
- adds me to baklava codeowners

### CODE REVIEW

**Review by overlisted — APPROVED** [review]
you reformatted raw.ts once again but ok

**Comment by BronzW** [comment]
How does it look?

**Comment by amitojsingh366** [comment]
> 
> 
> How does it look?

im not proficient at elixir so im still working on that, other things are done

**Comment by amitojsingh366** [comment]
ok it's ready and tested now

**Comment by amitojsingh366** [comment]
ok it's ready now

**Review by overlisted — APPROVED** [review]

**Review by ajmnz — APPROVED** [review]

**Pull request merged**
