### PR TITLE
Update Sound Effects

### PR DESCRIPTION
**Pull request by MrDogeBro**
## Description

This PR updates the four sound effects present in DogeHouse at the time (mute, unmute, mention, invite). The aim was to make the sounds a little nicer as well as make all of the sounds follow a same general theme and be consistent. For that reason, all of the sounds have the same base sound and then have been tweaked slightly sometimes for what I fit felt the sound. For these sounds I took inspiration from the existing DogeHouse sound effects as well as a little bit of Discord influence.

If you would like any changes to be made to the sounds, please let me know as I would be happy to make modifications. The sound files will be listed below for your convenience. Thanks for taking the time to look over this PR!

## Sound Files

Below are the sound files. These are meant for preview. These are mp4 because that is how GitHub allows me to upload them to this PR but the sounds in the sound effects folder are wav files and exported at a sample rate of 48k. Thanks!

https://user-images.githubusercontent.com/35872177/115148570-2551f500-a02e-11eb-8f67-ba6f30a1c9b6.mp4

https://user-images.githubusercontent.com/35872177/115148563-22ef9b00-a02e-11eb-968a-4cae00028dc4.mp4

https://user-images.githubusercontent.com/35872177/115148566-23883180-a02e-11eb-98ff-41bab12ff4fb.mp4

https://user-images.githubusercontent.com/35872177/115148567-2420c800-a02e-11eb-9d22-7df030e9005b.mp4

### CODE REVIEW

**Comment by dk-raw** [comment]
Pretty good work, but Ben has the last word on these kind of PRs

**Comment by dk-raw** [comment]
@benawad what do you think?

**Comment by BronzW** [comment]
If I'm aloud to give my opinions on this, I prefer the prior sound effects.

**Comment by benawad** [comment]
I'm indifferent about the sound, I'll let the community decide

**Comment by dk-raw** [comment]
The mute and unmute I personally think they are better than what we have now. I am not that sure about the Invite and ping though.

**Comment by MrDogeBro** [comment]
> The mute and unmute I personally think they are better than what we have now. I am not that sure about the Invite and ping though.

I can agree with you there to an extent — the main ones that I liked more were the mute and unmute but I just did all of them for the sake of consistency — but if everyone prefers I can make it so it just replaces the mute and unmute and not the ping and invite sounds — well see what everyone thinks.

**Review by ajmnz — APPROVED** [review]
It's a yes from me

**Comment by MrDogeBro** [comment]
> It's a yes from me

@ajmnz Yes to mute and unmute or to all of them?

**Comment by ajmnz** [comment]
> > It's a yes from me
> 
> @ajmnz Yes to mute and unmute or to all of them?

All of them

**Pull request merged**
