### PR TITLE
Added Ladin Translation

### PR DESCRIPTION
**Pull request by SpeckyYT**

### CODE REVIEW

**Comment by dk-raw** [comment]
please use `yarn commit` or `yarn commit:signed`

**Comment by SpeckyYT** [comment]
> please use `yarn commit` or `yarn commit:signed`

I'm getting this result: `No files added to staging! Did you forget to run git add?`
I never used yarn, so not sure what I have to do or what else

**Comment by amitojsingh366** [comment]
> > please use `yarn commit` or `yarn commit:signed`
> 
> I'm getting this result: `No files added to staging! Did you forget to run git add?`
> I never used yarn, so not sure what I have to do or what else

run the command `git commit --amend -m "feat(kibbeh): translated into ladin"` and the push to fix the commit errors,
there is also a linting error you need to take care of

**Comment by SpeckyYT** [comment]
I'll reopen another PR since I'm having some issues.

**Pull request closed without merging**
