### PR TITLE
Updated CONTRIBUTING.md and README.md

### PR DESCRIPTION
**Pull request by FotieMConstant**
Hi, everyone. done some cleanup in the CONTRIBUTING.md and README.md
@benawad there's a section I moved from the README.md to CONTRIBUTING.md, created a section there for that(Please check it out). thought it'd be a great idea since it has to do with contribution.🙂

### CODE REVIEW

**Comment by benawad** [comment]
Could you update this with the new instructions on how to run locally

**Comment by FotieMConstant** [comment]
Sure, I’ll check on that when I get home!

**Comment by FotieMConstant** [comment]
Hey @benawad, all good! have a look! Moved the **new instructions on how to run locally** to the CONTRIBUTING.md... created a section there for it. and have a link in the  README.md file which links directly to that section.
Hope that helps!

**Comment by benawad** [comment]
keep the table for the structure it looks nice

**Comment by FotieMConstant** [comment]
> keep the table for the structure it looks nice

The table is intact! Didn’t change the structure. Just moved it to another file 🙂

**Comment by FotieMConstant** [comment]
Hey @benawad, all good now!

**Pull request merged**
