### PR TITLE
dev-env: Add Gitpod config

### PR DESCRIPTION
**Pull request by ajhalili2006**
This PR contains configuration and required tools to be installed during prebuilds for Gitpod SaaS and self-hosted. It also includes an `docker-compose.yml` (adapted from `.devcontainer/docker-compose.yml`, with only RabbitMq and Postgres included) to ensure you don't need to mess up with local development (AKA experience dependency hell), among other things.

### CODE REVIEW

**Comment by amitojsingh366** [comment]
what exactly is gitpod tho?

**Comment by ajhalili2006** [comment]
> what exactly is gitpod tho?

@amitojsingh366 Gitpod is an dev-environment-as-code service, looks like GitHub Codespaces, [but better.](https://www.gitpod.io/gitpod-vs-github-codespaces)

**Comment by overlisted** [comment]
why does this ide need a special config to work with a project

**Comment by ajhalili2006** [comment]
> why does this ide need a special config to work with a project

@overlisted While Gitpod can work out of the box without the configuration (`.gitpod.yml`), the problem is this project is some sort of monorepo (Erlang and Elixir are not pre-installed in `gitpod/workspace-full` image), so there's an custom `.gitpod.Dockerfile` (and of course, `docker-compose.yml` that I copied from `.devcontainer/docker-compose.yml` with only Postgres and RabbitMQ containers needed).

**Comment by ghost** [comment]
what's the point of gitpod when GitHub Codespaces exists?

**Comment by overlisted** [comment]
> what's the point of gitpod when GitHub Codespaces exists?

it doesn't yet (afaik)

**Comment by ajhalili2006** [comment]
Since I marked this as `ready for review` (removing the `WIP: ` prefix for GitLab users), you can test if the proposed Gitpod config in this PR works.

[Try it here](https://gitpod.io#github.com/MadeByThePinsHub/dogehouse), and let me know if anything breaks.

Speaking of `docker-compose.yml` file, please do `docker-compose up -d` manually as this is not yet tested.

**Review by benawad — CHANGES_REQUESTED** [review]
merge conflcits

**Comment by overlisted** [comment]
i could've solved them if i knew a little bit more docker

**Pull request closed without merging**
