### PR TITLE
Add the Privacy Policy and Terms of Service pages

### LINKED ISSUE #1837: Add a REAL privacy policy and terms of service!
**Is your feature request related to a problem? Please describe.**
The privacy policy is a rickroll and is required by COPPA law

**Describe the solution you'd like**
A privacy policy and terms of service page

### PR DESCRIPTION
**Pull request by hisamafahri**
Add the Privacy Policy and Terms of Service pages, and also fix #1837 

Links:
- Privacy Policy: `/privacy`
- Terms of Service: `/terms`

The content is still using lorem ipsum text since I don't know how to create the real privacy policy and terms of service document.

Both of them can be edit on:
- Privacy Policy: `kibbeh/src/modules/docs/PrivacyPolicy.tsx`
- Terms of Services: `kibbeh/src/modules/docs/TermsOfService.tsx`

Screenshots:

**Privacy Policy**
pp

*Terms of Service**
tos

**Footer**
bottom

Thanks!

### CODE REVIEW

**Comment by lorstenoplo** [comment]
I guess you should fix scroll bar look

**Comment by hisamafahri** [comment]
> I guess you should fix scroll bar look

Working on it

**Comment by hisamafahri** [comment]
Scrollbar updated:

scrollbar

**Comment by overlisted** [comment]
who designed this

**Comment by amitojsingh366** [comment]
@ajmnz what do you think?

**Comment by amitojsingh366** [comment]
also please do not make any design assumptions without first confirming with @ajmnz as if he/ben isn't ok with it your work will be wasted... you can contact him on the [discord server](https://discord.gg/wCbKBZF9cV) *(`ajb#2501`)*

**Comment by ajmnz** [comment]
I'm clearly against merging this, as imo legal stuff should be hosted in the landing page (which is yet to be designed) instead of the app.

**Comment by amitojsingh366** [comment]
> 
> 
> I'm clearly against merging this, as imo legal stuff should be hosted in the landing page (which is yet to be designed) instead of the app.

i dont have much experience with legal but what you said seems reasonable enough so ig we can close this pr?

**Comment by benawad** [comment]
I like rickroll better than lorem ipsum.

If you want to stick the real thing in: https://github.com/benawad/dogehouse/blob/staging/kofta/public/privacy-policy.html

**Pull request closed without merging**
