### PR TITLE
fix: add "waytoodank" to the waytoodank emote keywords

### LINKED ISSUE #1914: WAYTOODANK doesn't appear in autocomplete when typing :way, but it does appear when you type :dank
**Describe the bug**
When ":WAY", or any amount of letters that it starts with, WAYTOODANK doesn't appear in autocomplete, however, when ":dank" is entered, it does appear.

**To Reproduce**
1. type :way, or any amount of the letters it starts with

**Expected behavior**
The emote known as WAYTOODANK should appear in the autocomplete above the text box.

**Screenshots**
2021-04-09-11:06:45-screenshot

2021-04-09-11:06:58-screenshot

**What device are you on?**
A linux pc.

**Additional context**
I'm using Next.dogehouse on firefox

### PR DESCRIPTION
**Pull request by raikasdev**
Added "waytoodank" to the waytoodank emote keywords
Related to issue [https://github.com/benawad/dogehouse/issues/1914](https://github.com/benawad/dogehouse/issues/1914)

### CODE REVIEW

**Comment by vi241** [comment]
@TheOtterlord I was gone for a long time - can we merge more emotes?

**Comment by TheOtterlord** [comment]
> 
> 
> @TheOtterlord I was gone for a long time - can we merge more emotes?

Not unless they remove the same number of emotes. 
But we pretty much have a pause for now

**Comment by vi241** [comment]
ok

**Comment by vi241** [comment]
thank you

**Comment by TheOtterlord** [comment]
This is a fix, so I'm pretty sure this one is fine

**Review by vi241 — APPROVED** [review]

**Pull request merged**
