### PR TITLE
emotes work with lowercase & json is lowercase

### PR DESCRIPTION
**Pull request by theCow61**
Inconstant when typing out emotes and emojis so now with this it all gets converted to lowercase so you don't have to worry about accidentally using a upper case or not. Also re formats EmoteData so they are all lowercase names. @nadirabbas @rban123 helped on this.

### CODE REVIEW

**Review by HarrisonMayotte — APPROVED** [review]
Looks good to me!

**Comment by theCow61** [comment]
How do we force people to use lowercase names when PRing emotes.

**Comment by benawad** [comment]
@theCow61 we are not taking anymore emote prs

**Comment by theCow61** [comment]
@benawad can we squeeze in this DoughDoge?
image

**Comment by benawad** [comment]
@theCow61 yeah but kill 1 emote

**Pull request merged**
