### PR TITLE
Add button popovers with title attribute

### PR DESCRIPTION
**Pull request by KieranHolroyd**

### CODE REVIEW

**Comment by KieranHolroyd** [comment]
fixes #76

**Comment by benawad** [comment]
Doesn't the browser tooltip suck, shouldn't we use a tooltip library?

**Review by leandrasilver — CHANGES_REQUESTED** [review]
Looks good in terms of this issue raised.

Since this is a web app, and potentially looking for investors, we also need to think in terms of accessibility. Keyboard users will not be able to view the title attribute on buttons. As for screenreader users please, can you also add `aria label` attribute so users will also get this information, since the button itself has no text.

**Comment by KieranHolroyd** [comment]
tooltip libraries are kinda hit or miss imo, it's easy enough to implement one after the fact, +1 for the accessibility idea

**Comment by KieranHolroyd** [comment]
also if i'm honest, i don't wanna break things and i can't test the frontend without starting elixir, and i have no idea how to do that yet sorry

**Comment by MrMalloc** [comment]
What do you think about downsizing the svgs to 24x24 and adding a text below the icon.
Something like https://material.io/components/bottom-navigation
This would also solve #65 and #49

**Comment by leandrasilver** [comment]
> What do you think about downsizing the svgs to 24x24 and adding a text below the icon.
> Something like https://material.io/components/bottom-navigation
> This would also solve #65 and #49

+1

**Pull request merged**
