### PR TITLE
Improve link regex

### LINKED ISSUE #455: Ellipsis cause adjacent words to generate hyperlinks
**Describe the bug**
When I type an ellipsis between two words, it creates a link.

**To Reproduce**
1. Enter a room
2. Type "test...test"
3. The text will send you to a nonexistent url

**Expected behavior**
A link should not be generated

**Screenshots**
Screen Shot 2021-02-26 at 23 06 30

**What device are you on?**
MacBook (Retina, 12-inch, 2017), Latest MacOS Big Sur, Firefox 85.0.2

**Additional context**
If a regex was used, it should make sure that there is text between each dot.

### PR DESCRIPTION
**Pull request by nadirabbas**
Fixes #455 
somebody, please test this on Safari

### CODE REVIEW

**Comment by tejxv** [comment]
@nadirabbas i tested it on iOS and it has some bugs
image

**Comment by nadirabbas** [comment]
@tejxv  This was made to remove double dots. I'll take a look at slashes.

**Comment by tejxv** [comment]
yeah that seems to be working at least and let me know if you want me to test any specific usecases

**Comment by nadirabbas** [comment]
@tejxv put as many different links as you can 😂

**Comment by tejxv** [comment]
LOL alright then 😂

**Comment by nadirabbas** [comment]
@tejxv I am pushing the fix. Kindly check with that

**Comment by tejxv** [comment]
@nadirabbas  it's working just fine!
image

**Pull request merged**
