### PR TITLE
Updated LanguageSelector and corrected language codes

### PR DESCRIPTION
**Pull request by rzsxdev**
- Corrected some languages codes (sr-Latin -> sr-LATIN)
- Fixed labels and comments in LanguageSelector
- Added or modified dome emojis that were black flags
- Corrected the order so that everything is alphabetical except, for example, the German languages (de, de-AT, gsw) which are grouped together

**Tagalog and Basque are missing translation files (Also Nynorsk)**
Additionally, do you think it would be better if the languages are ordered like in Wikipedia with languages with Latin script first, then Cyrillic script, and so on?

### CODE REVIEW

**Comment by dk-raw** [comment]
`grc` is not a thing. ancient Greek is referred to as `ag-GR`

**Comment by rzsxdev** [comment]
I checked from [Wikipedia](https://en.wikipedia.org/wiki/Ancient_Greek) and other sources that Ancient Greek's language code was `grc`, but I did not find anything called `ag-GR`. However, I may be mistaken.

**Comment by dk-raw** [comment]
Being Greek myself, I have never heard of that language code again. `ag-GR` is the official code for the Ancient Greek

**Comment by dk-raw** [comment]
Correction. `grc` is referred to as Greek until 1453(whick was a pre-mature version of the modern Greek). The pure Ancient Greek (1000 B.C.) is `ag-GR`.

**Comment by rzsxdev** [comment]
Ok, I'll correct it then.

**Comment by dk-raw** [comment]
~~use `agr` for the Ancient Greek. It is more suitable~~
Edit:
use `grc` if you are following the ISO pattern. However I have never seen that before.

**Comment by rzsxdev** [comment]
So i'll keep it as it is?

**Comment by dk-raw** [comment]
> So i'll keep it as it is?

Keep it as it is If you are following the ISO standards for all languages.

**Pull request merged**
