### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by nadirabbas**
Solves #313

It just links to https://github.com/benawad/dogehouse/blob/prod/CHANGELOG.md
image

### CODE REVIEW

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
Looks good for an MVP, but I think the styles of the changelog data display component need to be improved and refined before further approval and merging.

**Comment by nadirabbas** [comment]
Yeah, any CSS changes are welcome. You are very good at CSS @ajmnz

**Comment by benawad** [comment]
I want to just link to the changelog on github for now instead of having it be a page on dogehouse

**Comment by nadirabbas** [comment]
@benawad I have now linked it to Github and removed extra components.

**Review by DGKSK8LIFE — APPROVED** [review]
LGTM

**Comment by DGKSK8LIFE** [comment]
Maybe have a master changelog md document that links to all the other changelogs?

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by ajmnz** [comment]
> Yeah, any CSS changes are welcome. You are very good at CSS @ajmnz

Appreciate it. I really really think every UI change must be first designed and approved. Improvising the design on the go is just gonna introduce more and more inconsistencies.

**Comment by nadirabbas** [comment]
@ajmnz yeah we scraped it anyway. Btw everybody is using predefined styles and components. So it is hard to be inconsistent in kofta.

**Comment by ajmnz** [comment]
> Maybe have a master changelog md document that links to all the other changelogs?

Versioning would be another reasonable approach too.

**Comment by benawad** [comment]
See netlify logs, you need to remove unused import and checkout the <Spinner /> component I added. If you like it, we don't need <Loader />

I'll setup semantic releases later to auto create changelogs

**Comment by nadirabbas** [comment]
Okay I was not sure why my checks keep failing.

**Comment by nadirabbas** [comment]
@benawad Which component did you add?

**Comment by benawad** [comment]
oh my bad, github stripped out my thing `<Spinner />`

**Comment by nadirabbas** [comment]
@benawad The checks have passed now 🥱

**Comment by nadirabbas** [comment]
Did you just add a new footer link? I see 5 now. @benawad

**Comment by ajmnz** [comment]
> Did you just add a new footer link? I see 5 now. @benawad

Yep, he added the _Origin Story_ (link to the yt video)

**Pull request merged**
