### PR TITLE
added an XXS size to the SingleUser component

### PR DESCRIPTION
**Pull request by goldyydev**
See #1324 for more info

### CODE REVIEW

**Review by HarrisonMayotte — APPROVED** [review]
👍🏼

**Comment by ajmnz** [comment]
You forgot to add it to the existing Storybook

**Comment by goldyydev** [comment]
> You forgot to add it to the existing Storybook

Nope, it's in there. the storybook fetches the sizes from the TypeScript interface

**Comment by ajmnz** [comment]
> > You forgot to add it to the existing Storybook
> 
> Nope, it's in there. the storybook fetches the sizes from the TypeScript interface

Yep, wasn't loading locally for some reason. Can you set `right: 1px;` and `bottom: -1px` to the online bubble? So it keeps consistent across different sizes.

**Comment by goldyydev** [comment]
Here ya go.

**Pull request merged**
