### PR TITLE
Added swedish translations

### PR DESCRIPTION
**Pull request by BronzW**
Added swedish translations, might need some lookover for spelling mistakes.

### CODE REVIEW

**Comment by ajmnz** [comment]
@nadirabbas shouldn't this be merged to `staging` instead of `new-design`?

**Comment by nadirabbas** [comment]
damn, they changed the default branch 😱

**Comment by nadirabbas** [comment]
@BronzW can you create a PR and set `staging` as the target branch?

**Comment by BronzW** [comment]
Sure! :D

**Comment by BronzW** [comment]
#683

**Pull request merged**
