### PR TITLE
Feature: unread messages number

### PR DESCRIPTION
**Pull request by carlosqsilva**
Captura de Tela 2021-02-14 às 17 45 32

### CODE REVIEW

**Comment by benawad** [comment]
I'm undecided on whether I want to show this. I think it's a little cleaner just to show only the bubble, but I will think on this.

**Comment by tanay-pingalkar** [comment]
> I'm undecided on whether I want to show this. I think it's a little cleaner just to show only the bubble, but I will think on this.

you should add this feature

**Comment by SamiTriki** [comment]
That could be a setting, I believe slack has it set up this way

**Comment by benawad** [comment]
You can't really see that message icon well anymore. I'm indifferent about showing the number, but if you want to go with a different design option, you can reopen.

**Pull request closed without merging**
