### PR TITLE
Following list: show offline users

### LINKED ISSUE #256: Active users being followed
If none of the users I follow are online, the list just says "no users found". It would be better if there are two sections called "Offline Users" and "Online Users" with the offline ones being faded and below the "Online Users" section.

### PR DESCRIPTION
**Pull request by nadirabbas**
Fixes #256

- Show green dot if the user is online
- Sort following/followers by online status

image

### CODE REVIEW

**Comment by benawad** [comment]
instead of having 2 tabs, I think I would prefer a green dot or something to indicate they are online

**Comment by nadirabbas** [comment]
@benawad Got it

**Comment by nadirabbas** [comment]
@benawad conflicts resolved

**Comment by benawad** [comment]
Sorting on the frontend is not enough because we are using pagination, will need to sort in the db query

I didn't realize this replaces the people icon, the point of that is to see what room the people you follow are in.

`FollowingOnlineList.tsx` needs to stay, but the backend query needs to grab non-online users too

**Comment by nadirabbas** [comment]
@benawad will do that

**Pull request closed without merging**
