### PR TITLE
Change language name in the selector to its native name

### PR DESCRIPTION
**Pull request by MaySoMusician**
We should have the language name in its native name, for example as in 'Deutsch' instead of 'German'. I borrowed the names from:
- https://www.mozilla.org/locales/
- 'Native name' from https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes , if mozilla page doesn't have the language

And also I fixed the language code of Nepali

### CODE REVIEW

**Comment by ermalsh** [comment]
You'll have to fix conflicts once I finish merging the rest of the new languages that were added recently. You'll also have to add native language label to the new ones.

**Comment by MaySoMusician** [comment]
Sure, so I'd be glad if you or someone let me know when all prs merged

**Comment by ermalsh** [comment]
> Sure, so I'd be glad if you or someone let me know when all prs merged

You may do so now :)

**Comment by MaySoMusician** [comment]
Ok I'll do it later soon

**Comment by milansusnjar** [comment]
@MaySoMusician you can replace 
Српски (Cyrillic) with Српски
and
Српски (Latin) with Srpski

**Comment by aronluka** [comment]
@MaySoMusician 
The "Ceština" has typo, it is supposed to be "Čeština"

**Comment by MaySoMusician** [comment]
@ermalsh All ready for review & merge

I also...
- Fixed language codes for Albanian, Swedish, Swiss German, with the locations of their translation files fixed (directory name)
- Added Korean, that is not yet registered to the language selector, fixed the directory name in the same way as above

**Comment by MaySoMusician** [comment]
@milansusnjar @aronluka Thanks for reporting! I changed those as you pointed out

**Comment by overlisted** [comment]
change owo english to "OwO Engwish"

**Comment by MaySoMusician** [comment]
@overlisted updated

**Comment by ermalsh** [comment]
LGTM

**Review by ermalsh — APPROVED** [review]

**Pull request merged**
