### PR TITLE
Fixed type errors & Fixed #1458

### LINKED ISSUE #1458: When copying an emoji in the chat it doesn't include the colons on either side.
**Describe the bug**
When copying an emoji in the chat it doesn't include the colons on either side.

**To Reproduce**
1. Copy an emoji posted in the chat.
2. Attempt to past the emoji.
3. Observe that the colons that should be on either side are not present.

**Expected behavior**
It should have the colons around the emoji.

**Screenshots**
https://gyazo.com/4d18232c9aae536ae65631e274bd2de7

**What device are you on?**
Windows, Desktop, Chrome

### PR DESCRIPTION
**Pull request by goldyydev**
**That's about it.**
</br>
</br>
<sub>Feel free to Code Review my code 😀, I'll love some feedback!</sub>

### CODE REVIEW

**Comment by goldyydev** [comment]
My type fixes where really ghetto. If you want to, go ahead and make suggestions and I'll merge them to this PR.

**Review by amitojsingh366 — APPROVED** [review]
Seems good to me!

**Comment by amitojsingh366** [comment]
But @goldyydev i think setting types to `any[]` isn't the best idea. So maybe create a new type in `kofta/app/types.ts` for a more predictable output?

**Comment by goldyydev** [comment]
> But @goldyydev i think setting types to `any[]` isn't the best idea. So maybe create a new type in `kofta/app/types.ts` for a more predictable output?

That's exactly why I asked for a bit of help. I made a ghetto fix and will be happy if someone fixed it.

**Comment by vi241** [comment]
1) conflicts
2) what is the difference between `let x = 10` and `let x: any = 10`?

**Comment by goldyydev** [comment]
darn conflicts

> 2. what is the difference between `let x = 10` and `let x: any = 10`?

for some reason it had the unknown type in it by default

**Comment by vi241** [comment]
The conflicts are the react type instead of any

**Comment by vi241** [comment]
> darn conflicts
> 
> > 1. what is the difference between `let x = 10` and `let x: any = 10`?
> 
> for some reason it had the unknown type in it by default

Weird

**Review by vi241 — APPROVED** [review]
lgtm

**Pull request merged**
