### PR TITLE
Translated phrases for Brazilian Portuguese

### PR DESCRIPTION
**Pull request by c4f3firstt**
I translated some more phrases to PT-BR, I missed them in my previous PR

There are some words like: "debugger" that we dont have a specific translation, so works like that got adapted or stayed like the original one

### CODE REVIEW

**Comment by joaorodrs** [comment]
Is this related to #2362? I've done some more modifications too but you can overwrite with your changes if there's some conflict 👌🏾

**Comment by c4f3firstt** [comment]
Tbh I didnt saw the issues so I just translated because the translations were missing

**Comment by c4f3firstt** [comment]
I will take a look at your PR when I wake up, so we can """discuss"""

**Comment by vi241** [comment]
it looks ok

**Review by vi241 — APPROVED** [review]

**Comment by c4f3firstt** [comment]
@joaorodrs do you have any place where I can contact you? Because if you want we can translate everything again. Because we could have missed something

**Comment by joaorodrs** [comment]
> @joaorodrs do you have any place where I can contact you? Because if you want we can translate everything again. Because we could have missed something

`Joaorodrs#0735`

**Pull request closed without merging**
