### PR TITLE
feat(kibbeh): added a breadcrumbs feature to Kibbeh for better nav UX

### PR DESCRIPTION
**Pull request by christopher-talke**
Added breadcrumbs to the middle panel to help with Navigation UX, couldn't find anything in the Figma file so just based it off the tailwind config. 

image

### CODE REVIEW

**Comment by amitojsingh366** [comment]
this seems like a good feature but as I've mentioned before please confirm design related things with @ajmnz first. as if he/ben aren't ok with it then your work would just be wasted...

**Comment by amitojsingh366** [comment]
ill be closing on @ajmnz's request

**Comment by amitojsingh366** [comment]
or @TheOtterlord can close it too XD

**Comment by ajmnz** [comment]
If it's not on Figma it's because it hasn't been thought/planned yet.

**Comment by christopher-talke** [comment]
@ajmnz yeah fair enough, gave it a fair crack anyway. 

It would be worth considering, it does make navigation a little bit less painless.

Thanks for your time gents. 🙏🏽

**Pull request closed without merging**
