### PR TITLE
🐕

### PR DESCRIPTION
**Pull request by theCow61**
🐕

### CODE REVIEW

**Comment by reqster** [comment]
🐕

**Comment by RicoToothless** [comment]
LGTM

**Review by ajhalili2006 — COMMENTED** [review]
Looks kinda cursed.

**Comment by theCow61** [comment]
Merge it.

**Review by willdoescode — APPROVED** [review]
🧏‍♀️

**Comment by willdoescode** [comment]
merge. 🧏‍♀️

**Comment by grkek** [comment]
This cured my AIDS

**Comment by theCow61** [comment]
These are common sense changes.

**Comment by LuanHimmlisch** [comment]
This cured my terminal retardness

**Comment by LuanHimmlisch** [comment]
I found the love of my life thanks to this pull!!

**Comment by vytskalt** [comment]
merge this

**Review by ghost — APPROVED** [review]

**Comment by xiuxiu62** [comment]
just wait till we get dogehash working

**Comment by LuanHimmlisch** [comment]
@grkek someone banned me from the chat right before you removed admins lol

**Review by ottx96 — APPROVED** [review]

**Comment by willdoescode** [comment]
It got merged!

**Pull request merged**
