### PR TITLE
Added Pig Latin Novelty Language 

### PR DESCRIPTION
**Pull request by Hypercoded**
got bored, wanted to add pig latin

### CODE REVIEW

**Comment by dk-raw** [comment]
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

**Comment by Hypercoded** [comment]
> please follow the proper pattern for commit messages _(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)_
> 
> to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`
> 
> to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

I attempted to fix the commit but instead it just added a new one instead of overwriting

**Comment by Hypercoded** [comment]
Nevermind, realized my mistake

**Comment by amitojsingh366** [comment]
@Hypercoded you messed the commits up again
image

**Comment by Hypercoded** [comment]
> @Hypercoded you messed the commits up again
> image

Should I just close this PR, copy the code over to a different one and then open a new PR?

**Pull request closed without merging**
