### PR TITLE
Fixed an issue when putting large words (or spam) into a RoomCard's SubText would cause the text to overlap away from the card

### PR DESCRIPTION
**Pull request by goldyydev**
Hey maintainers,

While trying to break the components I spotted this issue so here we are with me making a pull request. (Hopefully I didn't fuck anything up)

### CODE REVIEW

**Comment by nadirabbas** [comment]
please pull from `staging`, otherwise `new-design` will get merged into `staging`

**Comment by vi241** [comment]
Isn't it in the CONTRIBUTING.MD ?

**Comment by nadirabbas** [comment]
@ofsho probably not, that's why there have been 10+ contributions with wrong source branches.

**Comment by vi241** [comment]
oh, we should fix it

**Comment by vi241** [comment]
@nadirabbas Fork the repo and create your branch (usually named patch-%the number of PRs you've already made%) from staging.

its there

**Pull request closed without merging**
