### PR TITLE
Add de translation of word Discord

### PR DESCRIPTION
**Pull request by 1kvsn**
Fix for: https://github.com/benawad/dogehouse/issues/705

### CODE REVIEW

**Review by gruselhaus — CHANGES_REQUESTED** [review]
`kofta/public/locales/de/translation.json` contains the german translations not the dutch translations

**Comment by gruselhaus** [comment]
@nadirabbas the made changes are invalid

**Comment by gruselhaus** [comment]
@1kvsn added a `dutch` translation to the German translations file

**Comment by nadirabbas** [comment]
how?

**Comment by nadirabbas** [comment]
`de` is dutch?

**Comment by gruselhaus** [comment]
`de` is German. But he added a `dutch` word (`Onenigheid`) to the `de` translations

**Comment by nadirabbas** [comment]
sorry i don't know dutch or german. @1kvsn ?

**Comment by gruselhaus** [comment]
No worries 😄 I believe there is not dutch translation at this time

**Pull request merged**
