### PR TITLE
Hyperhypebeast refactoring 1

### PR DESCRIPTION
**Pull request by ityonemo**

### CODE REVIEW

**Comment by ityonemo** [comment]
HyperHypeBeast refactoring, part I.  Beef module group.  The stateful center of the Kousa.

Next step: write tests against each database context and then refactor.
- [x] user
- [ ] user_preview
- [ ] user_block
- [ ] room
- [ ] room_permission
- [ ] room_block
- [ ] follow

@benawad want a general thumbs up/thumbs down before diving too deep into this

**Comment by benawad** [comment]
This sounds good to me

**Comment by ityonemo** [comment]
tests are generally complete on all usage of the "user" context.  Next steps
1. rename user schema module
2. separate changeset from schema
3. write in shims for all context functions in the "Data" modules.
4. identify all locations that call the context functions and write tests for these spots.
5. delete the "Data" module, replacing with the shimming functions.
6. refactor ad hoc user test
7. split off the work for the other tables into their own gh tasks/prs

**Comment by benawad** [comment]
I'm almost done with scheduled rooms, then I'll merge this in

**Pull request merged**
