### PR TITLE
fix(kofta): realigns 'add to calendar' button back to original place …

### LINKED ISSUE #1460: Edit & Delete button for Scheduled Rooms pushes "Add to Calendar" button to the left
**Describe the bug**
When creating a scheduled room, you'll have the Edit & Delete button there because you own the scheduled room. But, the Add to Calendar button is moved to the side.

**To Reproduce**
1. Go to the Scheduled Rooms button
2. Schedule a test room or see an already scheduled room that you own
3. See error

**Expected behavior**
Make the "Add to Calendar" button below the Edit & Delete button

**Screenshots**
image

**What device are you on?**
Chromebook

### PR DESCRIPTION
**Pull request by Harry-Developer**
…on owned scheduled cards

When creating a scheduled event the 'add to calendar' button moves between date and edit, this
places it back to the right side of the card

fix #1460

Hi, first ever oepn source PR, please let me if anything needs changing and/or what I did wrong/could be improved. Thanks!

### CODE REVIEW

**Review by drvladb — APPROVED** [review]
Looks good!
image

**Comment by samarmohan** [comment]
Looks good except the new design is out so this won't be needed.

**Comment by drvladb** [comment]
@samarmohan I think that the old design will remain an option, and it is still supported because the new design is not yet ready (and is far from so). Plus, this is a fix, not a feature, so these are still reviewed.

**Comment by ermalsh** [comment]
Looks good. We'll still keep this change even though new design is in prog.

**Pull request merged**
