### PR TITLE
fix(build): Fix environment variables

### PR DESCRIPTION
**Pull request by ghost**
Fixes the missing environment variables so that when compiling the back end, will not give an error.

### CODE REVIEW

**Comment by amitojsingh366** [comment]
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

**Comment by samarmohan** [comment]
@amitojsingh366  isn't force pushing bad?

**Comment by amitojsingh366** [comment]
> 
> 
> @AmitGolden isn't force pushing bad?

huh? who is @AmitGolden

**Comment by samarmohan** [comment]
GitHub autocomplete bad.

**Comment by samarmohan** [comment]
@josh-codes I'll implement these changes in #2637 so nothing overlaps. Please close this. If you disagree, just respond and we'll discuss.

**Pull request merged**
