### PR TITLE
Added THAI language

### PR DESCRIPTION
**Pull request by 37r**

### CODE REVIEW

**Comment by ajmnz** [comment]
Could you set the base to `staging`?

**Comment by 37r** [comment]
> Could you set the base to `staging`?

Done.

**Comment by nadirabbas** [comment]
You need to pull from `staging`, not `new-design`. Otherwise this will add `kibbeh` to `staging`.

**Comment by nadirabbas** [comment]
please open another PR with `staging` as the source branch with new changes.

**Pull request closed without merging**
