### PR TITLE
Update README: Extend local installation instructions and improve project file structure

### PR DESCRIPTION
**Pull request by ajmnz**
Extended the local installation instructions (although I only have tested them on macOS) and changed the current file structure for a more visual directory tree.

> Local installation instructions might need to be moved to CONTRIBUTING as README is starting to get cluttered.

### CODE REVIEW

**Comment by ajmnz** [comment]
Someone please confirm that the instructions on platforms other than mac actually work.

**Comment by ajmnz** [comment]
Solves #255, #234 (potentially), #218, #179, and other Docker-related issues (as now it isn't needed to start the dev version).

**Comment by nadirabbas** [comment]
shawarma wont work on windows. you have to have docker or some other os

**Comment by ajmnz** [comment]
> shawarma wont work on windows. you have to have docker or some other os

Not even with WSL?

**Review by PoseidonCoder — APPROVED** [review]
this looks great

**Comment by nadirabbas** [comment]
yes it will work with WSL

**Pull request merged**
