### PR TITLE
added translation to user profile and follow list page

### PR DESCRIPTION
**Pull request by AuroPick**
added translation to user profile and follow list page, now follow button translating

### CODE REVIEW

**Comment by nadirabbas** [comment]
why did you have to add the same keys twice?

**Comment by AuroPick** [comment]
I did because they are two different page. Shouldn’t i

**Comment by ermalsh** [comment]
Please fix conflicts. Also, if it's a common repeating translation key, just add it to commons instead of it's own category.

**Comment by ermalsh** [comment]
One last conflict to fix and should be good to go. @AuroPick

**Pull request merged**
