### PR TITLE
Add language label to improve accessibility score

### PR DESCRIPTION
**Pull request by shareef99**
## Add label for language to improve accessibility score

For more details, please refer to #765

### CODE REVIEW

**Comment by benawad** [comment]
can you fix it so it doesn't change formatting

**Comment by shareef99** [comment]
@benawad I didn't get it, can you explain?

**Comment by nadirabbas** [comment]
@shareef99 I think @benawad is telling you to not change the file spacing (maybe you have prettier format on save)

**Comment by shareef99** [comment]
@nadirabbas ah! I got it now, thanks

**Pull request closed without merging**
