### PR TITLE
Language selector made more readable

### PR DESCRIPTION
**Pull request by HasanMdArik**
Answer to issue #819

### CODE REVIEW

**Review by andrewroblesdev — APPROVED** [review]
Much nicer to look at

**Comment by benawad** [comment]
@MohammadArik you have a merge conflict

**Comment by HasanMdArik** [comment]
Ok I will be looking into the problem. Thanks!

**Comment by andrewroblesdev** [comment]
@MohammadArik I am happy to help resolve the merge conflict if you need it. Just hmu on Discord if you have any issues.

**Comment by nadirabbas** [comment]
there were more languages added after you pulled from `staging`. you may have to also add language labels for those new ones.

**Comment by HasanMdArik** [comment]
@nadirabbas yes this is the case. That was midnight in my region so I didn't try again. I am making it work in a bit. @andrewrobles thanks bro for trying to help me. But I don't have discord. You have LinkedIn or Facebook?

**Pull request closed without merging**
