### PR TITLE
Add peepoLove Emote

### PR DESCRIPTION
**Pull request by okdargy**
Add peepoLove Emote
peepoLove

### CODE REVIEW

**Comment by vi241** [comment]
We dont have need more emojis

**Comment by VottusCode** [comment]
tf

**Comment by vi241** [comment]
What?

**Comment by VottusCode** [comment]
@ofsho Why not expand the emote library?

**Comment by vi241** [comment]
Because ben said

**Comment by vi241** [comment]
I would be happy to

**Comment by VottusCode** [comment]
@benawad ????

**Comment by vi241** [comment]
what, no dont

**Comment by VottusCode** [comment]
wdym

**Comment by imansour12** [comment]
This is confusing.

**Comment by VottusCode** [comment]
agreed

**Comment by jamesql** [comment]
No, ben himself said to close PR's regarding adding new emote, wether this will change in the future I do not know, but as of right now we will not accept new emote PR's

**Pull request closed without merging**
