### PR TITLE
fix(kibbeh): fix #2483 - fix responsive issue of user follow buttons

### LINKED ISSUE #2483: follow user button is not responsive in mobile view
IMG_20210502_030252
IMG_20210502_030450

### PR DESCRIPTION
**Pull request by Alirezamxz**

### CODE REVIEW

**Comment by amitojsingh366** [comment]
this issue seems to be fixed now and hence there is no need for this pr

**Comment by amitojsingh366** [comment]
im reopening this as the issue has resurfaced

**Comment by amitojsingh366** [comment]
why is it shifted towards the left in normal mode? 
image

**Comment by Alirezamxz** [comment]
What is the screen size ? I am checking.

**Pull request merged**
