### PR TITLE
Feature/language al

### PR DESCRIPTION
**Pull request by erlinh**
Added Albanian translations.

### CODE REVIEW

**Comment by ermalsh** [comment]
> Added Albanian translations.

Needs rebase/conflict fixed.  👍 for albanian translation though, since I'm Albanian

**Comment by erlinh** [comment]
> > Added Albanian translations.
> 
> Needs rebase/conflict fixed. 👍 for albanian translation though, since I'm Albanian

Good job on resolving the conflict. Albanian here as well 😊

**Comment by ermalsh** [comment]
> > > Added Albanian translations.
> 
> > 
> 
> > Needs rebase/conflict fixed. 👍 for albanian translation though, since I'm Albanian
> 
> 
> 
> Good job on resolving the conflict. Albanian here as well 😊

You will need to pull from staging and fix the conflicts still.

**Comment by ermalsh** [comment]
Last thing, it looks like your branch came from new-design and non staging.

You'll need to branch out of benawad:staging and make your changes in there, then create a new PR. This PR source branch has all of the new-design changes that shouldn't be in benawad:staging yet.

(Not your fault, the default branch is set to new-design and people usually just branch straight out from there instead of switching to staging)

**Comment by erlinh** [comment]
> Last thing, it looks like your branch came from new-design and not staging.
> 
> You'll need to branch out of benawad:staging and make your changes in there, then create a new PR. This PR source branch has all of the new-design changes that shouldn't be in benawad:staging yet.
> 
> (Not your fault, the default branch is set to new-design and people usually just branch straight out from there instead of switching to staging)

Thanks for pointing it out. Didn't even notice that. I'm going to close this PR then 👍

**Pull request closed without merging**
