### PR TITLE
Add MobileNav Component

### PR DESCRIPTION
**Pull request by bansalarnav**
Created MobileNav component

### CODE REVIEW

**Comment by goldyydev** [comment]
Can you please update the Storybook so it would work by default?

**Comment by bansalarnav** [comment]
It errors out as the component uses useRouter but it isn't available in storybook. If you have any workaround for it please tell so that I can make it work

**Comment by bansalarnav** [comment]
Storybook works now. Please inspect the page and reduce page width to see the component as I added a media query to only show the component if width < 640px

**Review by goldyydev — APPROVED** [review]

**Review by goldyydev — CHANGES_REQUESTED** [review]
A bit of an update, ben has removed the Sm prefix from icons, so please follow this PSA on this commit so we won't have weird names flowing around

image

**Comment by bansalarnav** [comment]
> A bit of an update, ben has removed the Sm prefix from icons, so please follow this PSA on this commit so we won't have weird names flowing around
> 
> image

I already changed that. Icons don't have the Sm prefix

**Review by HarrisonMayotte — APPROVED** [review]

**Pull request merged**
