### PR TITLE
Added owo english language

### PR DESCRIPTION
**Pull request by Szoniko**
Added owo english language to the language selector as nadirabbas told me to.

### CODE REVIEW

**Comment by drvladb** [comment]
Are you sure that you included the "OwO english" translation.json file?

**Comment by Szoniko** [comment]
> Are you sure that you included the "OwO english" translation.json file?

it's in another pull request, I have no idea how github works, if it's a problem I'll try to change that

**Comment by drvladb** [comment]
Can you link that PR?

**Comment by Szoniko** [comment]
> Can you link that PR?

https://github.com/benawad/dogehouse/pull/1080

**Comment by drvladb** [comment]
Here's the problem, your language selector code and the actual language are on two different branches (patch-3 for the translation, patch-4 for the selector). You need to commit the language selector code to patch-3 (so that everything is in the same place).

**Comment by Szoniko** [comment]
> Here's the problem, your language selector code and the actual language are on two different branches (patch-3 for the translation, patch-4 for the selector). You need to commit the language selector code to patch-3 (so that everything is in the same place).

ok, I'll do that, is there a way to remove this request?

**Comment by drvladb** [comment]
You can click the close PR button to close this PR.

**Pull request closed without merging**
