### PR TITLE
feat(kibbeh): add md size variant for tablets

### PR DESCRIPTION
**Pull request by Mayowa-Ojo**
add medium size variant in UserAvatar/SingleUser for tablet view

#1390

### CODE REVIEW

**Review by bansalarnav — APPROVED** [review]
Seems fine to me 👍

**Review by BronzW — APPROVED** [review]
epic

**Review by vi241 — COMMENTED** [review]
Can you move md before the sm?

**Comment by vi241** [comment]
but anyways it looks fine

**Comment by Mayowa-Ojo** [comment]
@ofsho will do that

**Comment by vi241** [comment]
ok

**Comment by Mayowa-Ojo** [comment]
Done. But the deployment is failing due to limited resource. Can a deployment be triggered without making commits?

**Pull request merged**
