### PR TITLE
add persian (fa) locale

### PR DESCRIPTION
**Pull request by mohammadjavad948**
add persian language support

### CODE REVIEW

**Comment by ermalsh** [comment]
@mohammadjavad948 Please add the language along with it's flag emoji to LanguageSelector.tsx component.

**Comment by mohammadjavad948** [comment]
@ermalsh ok

**Comment by mohammadjavad948** [comment]
@ermalsh  can i create another pull request ?

**Comment by ermalsh** [comment]
@mohammadjavad948 No it's ok, you've already fixed it and I've merged it. This is now all set.

**Comment by mohammadjavad948** [comment]
thanks

**Pull request merged**
