### PR TITLE
feat(kofta): added 2^7 new emotes (28x28)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by HarrisonMayotte — APPROVED** [review]
Looks good to me!

**Comment by drvladb** [comment]
https://github.com/benawad/dogehouse/issues/1109#issuecomment-800395187, yeah, that's not under a hundred

**Comment by jamesql** [comment]
2^6 should be fine

**Comment by vi241** [comment]
You deleted most of the emojis

**Comment by JesseCharlie** [comment]
> You deleted most of the emojis

FACT CHECK your claims.

Deleted emotes were duplicates. Check the file. Please.

**Comment by vi241** [comment]
Why do you have 1176+ lines?

**Comment by vi241** [comment]
and why are there duplicates?

**Comment by JesseCharlie** [comment]
> Why do you have 1176+ lines?

The more emotes that are added, the more lines are created.



> and why are there duplicates?

When I merged to staging to be ahead on commits, many lines were duplicates, so I removed them, so NOW there isn't and duplicates.

**Comment by vi241** [comment]
I think you should copy the EmoteData.ts file from kofta and add all of your emojis again because there are no duplicates in kofta

**Comment by vi241** [comment]
ok i will see

**Pull request merged**
