### PR TITLE
Make 2 emotes transparent

### PR DESCRIPTION
**Pull request by okdargy**
brokenHeart
takemymoney

### CODE REVIEW

**Comment by troler36** [comment]
I approve this

**Review by drvladb — APPROVED** [review]

**Comment by drvladb** [comment]
@dragonismcode Please provide some screenshots of the emotes in use.

**Review by samarmohan — APPROVED** [review]

**Comment by okdargy** [comment]
> @dragonismcode Please provide some screenshots of the emotes in use.

What do you mean? Like the transparent ones or the old ones?
image

**Review by ermalsh — APPROVED** [review]

**Comment by goldyydev** [comment]
Approved these as it is a bug fix, this does not add any new emojis.

**Pull request merged**
