### PR TITLE
Fix chat styling

### LINKED ISSUE #414: Woahhhh
image

### PR DESCRIPTION
**Pull request by nadirabbas**
Fixes #414 and #413 

(I had to pass in `className` prop to `Avatar`, otherwise, I had to use `style` attr, which we're afraid of. In this case, classes on the wrapper won't solve the issue)

### CODE REVIEW

**Comment by tanay-pingalkar** [comment]
have you made the scroll bar like it was before

**Comment by nadirabbas** [comment]
@tanay-pingalkar yes sire

**Comment by tanay-pingalkar** [comment]
And can you make height of emoji feature half of what it is now.....bcoz its looking ugly, i had made its height small but some changed that..make overflowY hidden in tailwind if possible..

**Comment by tanay-pingalkar** [comment]
please

**Pull request merged**
