### PR TITLE
Changed logo size in README.md (kibbeh)

### PR DESCRIPTION
**Pull request by BronzW**
Changed size of image to a bigger size (kibbeh, not staging)

### CODE REVIEW

**Review by bansalarnav — APPROVED** [review]

**Comment by bansalarnav** [comment]
tho i dont get the point of increasing a logo size in a README

**Comment by BronzW** [comment]
Looks nicer

**Comment by samarmohan** [comment]
There is no point in this.

**Comment by BronzW** [comment]
bruh

**Pull request closed without merging**
