### PR TITLE
fix(kibbeh): same message toast getting added in list

### LINKED ISSUE #2338: room gone error message stacks on top of each other
**Describe the bug**
clicking the back button to go to the previous page when the previous page is a room that no longer exists redirects you to the homepage again if you keep clicking back it keeps redirecting and displays the 'room gone' flash message everytime

**To Reproduce**
1. Go to a room
2. end it and you should be redirected to the home page
3. click the back button as many times as you want

**Expected behavior**
the error message should be displayed once, or display a 404 page instead.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by junedkhatri31**
Fix: [#2338](https://github.com/benawad/dogehouse/issues/2338), [#2157](https://github.com/benawad/dogehouse/issues/2157)

Same message won't be added again in the list. First old message will be removed and new message will be added at the end of the list to maintain duration and order.

### CODE REVIEW

**Comment by amitojsingh366** [comment]
please use proper commit messages *(`yarn commit` or `yarn commit:signed`)*

**Comment by junedkhatri31** [comment]
@amitojsingh366 Sorry about this. Will keep in mind next time. Should I raise another merge request with proper commit messages or this will work for now?

**Comment by amitojsingh366** [comment]
> @amitojsingh366 Sorry about this. Will keep in mind next time. Should I raise another merge request with proper commit messages or this will work for now?

you can rename your commits, read this for more info https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages

**Comment by junedkhatri31** [comment]
Done 😁

**Comment by junedkhatri31** [comment]
> > @amitojsingh366 Sorry about this. Will keep in mind next time. Should I raise another merge request with proper commit messages or this will work for now?
> 
> you can rename your commits, read this for more info https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages

Thanks

**Comment by amitojsingh366** [comment]
> > > @amitojsingh366 Sorry about this. Will keep in mind next time. Should I raise another merge request with proper commit messages or this will work for now?
> > 
> > 
> > you can rename your commits, read this for more info https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages
> 
> Thanks

np

**Pull request merged**
