### PR TITLE
Added Romanian Language

### PR DESCRIPTION
**Pull request by egoomni**

### CODE REVIEW

**Comment by slendidev** [comment]
No offense, looks like it's done with Google Translate. There are some basic errors in the translation that could've easily been solved

**Comment by benawad** [comment]
closing in favor of #894

**Comment by egoomni** [comment]
> No offense, looks like it's done with Google Translate. There are some basic errors in the translation that could've easily been solved

OK, but there are a couple mistakes on your side also ...  line 68 "goHomeMessage": "Nu te îngrijora. Poți",  and 69 "goHomeLinkText": "du-te acasă" ... which results in: "Nu te îngrijora. Poți du-te acasă".. but yes this can be easily solved) cheers!

**Comment by slendidev** [comment]
fixed thanks for pointing it out

**Pull request closed without merging**
