### PR TITLE
Added PartyParrot emote

### PR DESCRIPTION
**Pull request by ShahrozTanveer**

### CODE REVIEW

**Comment by ShahrozTanveer** [comment]
Added PartyParrot emote
PartyParrot

**Comment by amitojsingh366** [comment]
I like it 😂

**Review by amitojsingh366 — APPROVED** [review]

**Comment by ShahrozTanveer** [comment]
Added DogePls emote 
DogePls

**Comment by vi241** [comment]
I will review this

**Comment by vi241** [comment]
looking good

**Pull request merged**
