### PR TITLE
Removing alwaysOnTop property of splash screen

### PR DESCRIPTION
**Pull request by yummyweb**
This pr is based on a feature request by @amitojsingh366 where he said that the splash screen should not always be on top. So this pr does exactly that.

Tested on MacOS Mojave 10.14

### CODE REVIEW

**Comment by nadirabbas** [comment]
What's the rationale here? why shouldn't it be on the top tho?

**Comment by amitojsingh366** [comment]
@nadirabbas the always on top property makes it so it even comes over other apps. So if you're doing something and open dogehouse side by side you have like 2 seconds where you aern't able to perform any actions as dogehouse is on top of other apps

**Comment by amitojsingh366** [comment]
But i don't see why it requires 4000 lines of code. But i don't understand git much yet either.

**Comment by nadirabbas** [comment]
please reset the `pacakage-lock.json` to `ben/staging`

**Comment by yummyweb** [comment]
ok

**Comment by yummyweb** [comment]
@nadirabbas done. Please merge if the pr is fine.

**Comment by nadirabbas** [comment]
there are still changes in the lockfile. please reset

**Pull request merged**
