### PR TITLE
fix(kibbeh): add missing translation key

### PR DESCRIPTION
**Pull request by tithanayut**
- Add 6 missing translation key to kibbeh
- Already run yarn i18

### CODE REVIEW

**Comment by rzsxdev** [comment]
Also the top banner of the Language Selector still says "Language" and not the translation.

**Comment by tithanayut** [comment]
> Also the top banner of the Language Selector still says "Language" and not the translation.

Fixed. 

(The key already exists, no need to run yarn i18)

**Comment by ajmnz** [comment]
Fix conflicts please

**Comment by joaorodrs** [comment]
I don't know if this can be related to this issue, but the `"with"` word in the `RoomHeader.tsx` is not with the `useTypeSafeTranslation`, so it's not translating and this word also is missing in the translation files.
image

**Comment by tithanayut** [comment]
> Fix conflicts please

Fixed.



> I don't know if this can be related to this issue, but the `"with"` word in the `RoomHeader.tsx` is not with the `useTypeSafeTranslation`, so it's not translating and this word also is missing in the translation files.
> image

Yes, it is related. Fixed.

**Comment by tithanayut** [comment]
About 2 failing checks:

lint-and-test-kibbeh: Seems to fail because of code in default branch (staging). I fixed mine already.
Lint Commit Messages / commitlint: Too late to change my commit message.. now I know, will do it next time.

**Comment by rzsxdev** [comment]
I mentioned this is a previous pull request but words like "with" and "about" do not have direct translations in many languages. Instead they might depend of the noun itself and can alter the word order.

**Comment by tithanayut** [comment]
In that case I think leaving the word unchanged by not translating them in translation.json would be fine. Adding key to translation file would benefit the language that do have direct translation.

**Comment by ermalsh** [comment]
Fix conflicts please.

**Comment by tithanayut** [comment]
I could not edit failing commit message. Should I close this PR and reopen new one with all changes later?

**Comment by junedkhatri31** [comment]
> I could not edit failing commit message. Should I close this PR and reopen new one with all changes later?

you can rename your commits, read this for more info https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages

**Comment by BronzW** [comment]
> I could not edit failing commit message. Should I close this PR and reopen new one with all changes later?

Close and create a new if you feel it's easier I guess

**Comment by tithanayut** [comment]
I will close this PR first. Anyone who would like please take over my changes.

**Pull request closed without merging**
