### PR TITLE
perf(global): Upgraded a lot of packages (incl. nextjs)

### PR DESCRIPTION
**Pull request by goldyydev**
This PR upgrades a lot of packages (besides the ones that cause errors on update). A notable change
is NextJS, this upgrade should fix the issue where @benawad complains that NextJS doesn't cache
anything (according to them it is a 100-200ms difference) and an upgrade to webpack 5. I've already
tested most things on my machine but please give it a shot and test if anything's broken __before__
we push to production.

### CODE REVIEW

**Review by overlisted — APPROVED** [review]
make sure it compiles

**Comment by goldyydev** [comment]
> make sure it compiles

We can view it at https://dogehouse-git-fork-goldyydev-patch-29-benawad.vercel.app/ so ig it compiled successfully on the server side.

**Comment by benawad** [comment]
LGTM

**Review by benawad — APPROVED** [review]

**Comment by amitojsingh366** [comment]
last words, "LGTM"

**Review by amitojsingh366 — APPROVED** [review]

**Pull request merged**
