### PR TITLE
Better Dutch translation

### PR DESCRIPTION
**Pull request by GijsRommers**
Improved translations for the dutch language, this merges into prod

### CODE REVIEW

**Comment by daankent** [comment]
I see you changed unban to "verban". But in Dutch "verban" means: ban. So this I think this is an incorrect translation.

**Comment by overlisted** [comment]
also maybe you should change all 1-verb strings to infinitive verbs?

**Comment by GijsRommers** [comment]
> I see you changed unban to "verban". But in Dutch "verban" means: ban. So this I think this is an incorrect translation.

yeah true, accidently swapped two of them, fixed that now

**Comment by GijsRommers** [comment]
> also maybe you should change all 1-verb strings to their infinitive forms?

i'll get started on that, but im currently building on an already existing translation

**Comment by daankent** [comment]
While you're at it, maybe you can change banFromChat to "Verban uit de chat"  and change banFromRoom to "Verban uit de kamer".

**Comment by nadirabbas** [comment]
please pull from `staging`

**Comment by GijsRommers** [comment]
Literly said it merged into prod lma

**Comment by nadirabbas** [comment]
yeah i accidentally merged it into prod lmao

**Pull request merged**
