### PR TITLE
(kofta) Add bottom Translation

### PR DESCRIPTION
**Pull request by daggy1234**
Bottom is an up and coming spec popular with a wide variety of people. It is currently managed by the bottom software foundation and has a wide variety of implementations in various languages.  This allows dogehouse to become supportive towards bottoms..

Main Bottom Org::
https://github.com/bottom-software-foundation/

### CODE REVIEW

**Comment by vi241** [comment]
wtf?

**Comment by daggy1234** [comment]
perhaps the readme explains bottom better

https://github.com/bottom-software-foundation/bottom-rs/blob/need_top/README.md

**Comment by vi241** [comment]
ok

**Comment by vi241** [comment]
why change the gitignore?

**Comment by vi241** [comment]
why change the gitignore?

**Comment by daggy1234** [comment]
Uhh there were lots of yarn-error.log created, so I added them to the gitignore. No point in commiting a error log

**Comment by vi241** [comment]
oh ok

**Review by vi241 — APPROVED** [review]
All good

**Pull request merged**
