### PR TITLE
fix(yarn.lock): added downgrade of postcss-loader in kibbeh to yarn.lock

### PR DESCRIPTION
**Pull request by BronzW**

### CODE REVIEW

**Comment by goldyydev** [comment]
Instead of downgrading, maybe we could make the latest version work?

**Comment by benawad** [comment]
@goldyydev feel free to open a new pr fixing in new version

**Comment by amitojsingh366** [comment]
wait what was this pr for even. i had already fixed this before the pr?

**Comment by BronzW** [comment]
The yarn.lock still had the new version. Running `yarn` converted it into the downgrade.

**Comment by amitojsingh366** [comment]
oh lol

**Pull request merged**
