### PR TITLE
Update translation.json

### PR DESCRIPTION
**Pull request by halmasi**
fix some typos

### CODE REVIEW

**Comment by halmasi** [comment]
change some words to proper ones, and fix some typos

**Comment by vi241** [comment]
Which language?

**Comment by HarrisonMayotte** [comment]
@ofsho I believe Lefa but I'm not 100% positive on that

**Comment by vi241** [comment]
by "believe" do you mean you think the translations are good?

**Comment by HarrisonMayotte** [comment]
Not sure about the actual translation but from a brief look up of the abbreviated name-folder that it is in, I found conflicting answers so my best guess is Lefa but who knows.

**Comment by halmasi** [comment]
@ofsho Farsi (Persian)

**Comment by vi241** [comment]
@halmasi what?

**Comment by vi241** [comment]
Oh ok - sry for not understanding

**Pull request merged**
