### PR TITLE
feat: hover animations on follow buttons

### PR DESCRIPTION
**Pull request by ParmeetChanne**
Added hover animations on followers and following buttons 
Added transition on block and follow buttons

### CODE REVIEW

**Comment by benawad** [comment]
can you show a video for it?

**Comment by ParmeetChanne** [comment]
https://user-images.githubusercontent.com/67189839/117184469-69971080-adf6-11eb-95b1-c2d5f097c47c.mp4

This is the vid @benawad

**Comment by ParmeetChanne** [comment]
This also automatically adds transitions to other buttons, like the _"OK"_  ,  _"New Room"_  buttons in create room modal , and _"Yes"_ button during logout, _"voice"_ and _"sound"_ settings button in UserProfile, _"save"_ button in EditProfile
Thus giving a smooth user experience

**Comment by ParmeetChanne** [comment]
So I see what's going on: 
The last test of _kibbeh/src/ui/tests/Button.spec.tsx_ is failing as it isn't matching the snapshot
You have to regenerate the snapshot, as I had made the changes in the button (transitions only) -> `jest --updateSnapshot`

**Comment by benawad** [comment]
@ParmeetChanne you have to run update snapshot locally and push it

**Pull request merged**
