### PR TITLE
fix(kibbeh/src/ui/profiletabs.tsx): about button in profileTab spacin…

### PR DESCRIPTION
**Pull request by chuddyjoachim**
tab button adjustment

### CODE REVIEW

**Comment by amitojsingh366** [comment]
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

**Comment by ghost** [comment]
Oh my god that commit message pains me.

**Comment by chuddyjoachim** [comment]
> @amitojsingh366 i did use `yarn commit` and answered the questions asked.

**Comment by amitojsingh366** [comment]
> 
> 
> > @amitojsingh366 i did use `yarn commit` and answered the questions asked.

the scope you gave is wrong, you current scope is `kibbeh/src/ui/profiletabs.tsx` change that to `kibbeh` by running the following command and pushing `git commit --amend -m 'fix(kibbeh): about button in profileTab spacing adjustment'`

**Comment by chuddyjoachim** [comment]
> @amitojsingh366 yeah the commit message, sorry about that, will amend in a bit

**Comment by ghost** [comment]
why'd you close it?

**Comment by samarmohan** [comment]
why

**Pull request closed without merging**
