### PR TITLE
mods cant move other mods to listeners section now

### PR DESCRIPTION
**Pull request by nadirabbas**

### CODE REVIEW

**Review by benawad — CHANGES_REQUESTED** [review]
Looks good, but can you put your test in `set_role_test` and use the newer api. In the future, don't worry about writing legacy tests those are going to get thrown away.

**Comment by nadirabbas** [comment]
@benawad which one is the newer API?

**Comment by benawad** [comment]
@nadirabbas set_role

**Comment by benawad** [comment]
look at the tests in set_role_test and copy paste one with a mod on mod

**Comment by nadirabbas** [comment]
@benawad test moved from legacy to new

**Pull request merged**
