### PR TITLE
Update .prettierrc.js

### PR DESCRIPTION
**Pull request by HonbraDev**

### CODE REVIEW

**Comment by samarmohan** [comment]
What was the point of this? @goldyydev @amitojsingh366 @overlisted please close.

**Comment by simonri** [comment]
Lmao

**Comment by overlisted** [comment]
[Reopen pull request]
[Merge]

**Comment by samarmohan** [comment]
Ok, you scared me there

**Comment by amitojsingh366** [comment]
> What was the point of this? @goldyydev @amitojsingh366 @overlisted please close.

bro i was sleeping wtf is this

**Pull request closed without merging**
