### PR TITLE
Added support for #488 - UI Internationalization

### PR DESCRIPTION
**Pull request by ermalsh**
**Added support for #488 - UI Internationalization:**

- i18next integration
- created translation select dropdown component
- to start, implemented footer translation strings for es, en, de, fr, pt

**Added dependencies/libraries:**

- i18next
- react-i18next
- react-dropdown-select

**TODO:**

- further translations (need help w/ this)

### CODE REVIEW

**Comment by FotieMConstant** [comment]
I could work on the french translation!

**Comment by Doges** [comment]
Feel free to @ me to work on the Brazilian Portuguese translation

**Comment by benawad** [comment]
Looks good, I'm going to leave this open until we extract more strings

**Comment by ermalsh** [comment]
@benawad Great! I can assist with recruiting some users to help w/ the strings. I will also add Brazilian Portuguese translation base so @Doges can pick up and work on. @FotieMConstant feel free to pull and push French translations when you can. Thank you all!

P.S. I will work on adding additional EN strings to encompass a majority of the text elements on the FE tonight.

**Comment by nadirabbas** [comment]
Can work on Urdu translation :)

**Comment by ermalsh** [comment]
> Can work on Urdu translation :)

@nadirabbas cool! Do you know the International Language code for Urdu? Is it UR?

**Comment by KristofKekesi** [comment]
Can help with the Hungarian translation.

**Comment by ermalsh** [comment]
> Can help with the Hungarian translation.

@KristofKekesi Added Hungarian, ready to be translated!

**Comment by jabezborja** [comment]
I can work for Tagalog (ph) translation

**Comment by ajmnz** [comment]
I can do Spanish (es) and Catalan (ca) 👍🏼

**Comment by miguelcarreiro** [comment]
I can work on European Portuguese (pt-pt) translation

**Comment by DGKSK8LIFE** [comment]
If you need a French or Arabic translation I could help.

**Comment by metecan** [comment]
Can work on Turkish translation.

**Comment by alkarem34** [comment]
can help with Arabic (Modern Standard Arabic) (ar)

**Comment by DGKSK8LIFE** [comment]
@Karem34 I wonder if it would be possible to translate to each Arabic dialect. الفصحى could work too though

**Comment by nadirabbas** [comment]
we need RTL support for that

**Comment by DGKSK8LIFE** [comment]
@nadirabbas RTL?

**Comment by nadirabbas** [comment]
@DGKSK8LIFE Right-to-left text direction.

**Comment by alkarem34** [comment]
@DGKSK8LIFE there are too many dialects to count, most arabs will understand msa

**Comment by DGKSK8LIFE** [comment]
>@DGKSK8LIFE there are too many dialects to count, most arabs will understand msa

Yeah agreed. Especially those with internet access. And the functionality is pretty simple/clear so msa should work.

**Comment by zohnannor** [comment]
Can work on russian translation.

upd: nvm someone already did it without mentioning

**Pull request merged**
