### PR TITLE
Fixes #233: Avatar disappears on home screen when window width is very small

### LINKED ISSUE #233: Avatar disappears when window width is very small
Avatar profile picture shrinks to the point it disappears when reducing screen width very small.

Could be fixed by adding some flex-wrap and gap and remove some margin :)

### PR DESCRIPTION
**Pull request by SuperSonicHub1**
Screenshot

Fixes #233.

* Removes margin from wrapper `<div>`s encasing buttons
* Adds [flex-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap) to `<div>` wrapping around buttons

### CODE REVIEW

**Comment by SuperSonicHub1** [comment]
I don't understand why I cannot resolve my changes in my editor or VS Code. I can see why the package lock might be causing conflicts, but not my `.tsx` changes.

**Comment by SuperSonicHub1** [comment]
@benawad How do I see why deployment failed? I made a Vercel account, but when I click on `Details`, I'm taken to a 404.

**Review by willdoescode — APPROVED** [review]
😃

**Review by dhenson02 — COMMENTED** [review]
:)

**Review by theCow61 — COMMENTED** [review]
😀

**Review by theCow61 — CHANGES_REQUESTED** [review]
Could this be done in doge lang?

**Review by dhenson02 — APPROVED** [review]

**Pull request merged**
