### PR TITLE
Experimental ingress modules

### PR DESCRIPTION
**Pull request by dark-elixir-shibe**

### CODE REVIEW

**Comment by dark-elixir-shibe** [comment]
@benawad not hooked into the WS pipeline yet, just wanted you to get a glance at it before I work on connecting them and see if you understand what's going on and if you have any questions

**Comment by goldyydev** [comment]
@benawad

**Comment by dark-elixir-shibe** [comment]
note: this is still draft status, I wanted to take comment on it before completing hooking it up to WS subsystem

**Comment by benawad** [comment]
I roughly understand whats going on, but we should do a call when you have time to walk through it.

**Comment by ityonemo** [comment]
going to convert to non-draft status.  None of the code in this PR is in an actual execution path.

**Comment by ityonemo** [comment]
lol it looks like we are reaching concurrency timeouts in CI

**Pull request merged**
