### PR TITLE
Electron wrapper for dogehouse

### PR DESCRIPTION
**Pull request by arhammusheer**
I added an electron wrapper for the website in the folder `baklava`.

- To build electron apps: use package.json scripts of the folder.
- Uses electron-packager to build electron apps
- Loads content from the website.

Supports M1 builds.

### CODE REVIEW

**Comment by nadirabbas** [comment]
You can use .env.local in the kofta folder, it is already in the gitignore

**Comment by fkoeppling** [comment]
Nice work Arham!

**Comment by benawad** [comment]
I'm already using Falafel/hummus/tabouleh for another project and I don't want to confuse them in my brain, can you pick a different food. Also can you add this to the readme chart so people know whats in this folder. Other than that, looks good.

**Comment by arhammusheer** [comment]
Changed name from falafel to baklava. Also updated README.md to reflect changes.

**Pull request merged**
