### PR TITLE
I accidentally merged in to new-designm Revert "Added swedish translations"

### PR DESCRIPTION
**Pull request by nadirabbas**
Reverts benawad/dogehouse#676

### CODE REVIEW

**Comment by ajmnz** [comment]
@nadirabbas I think that happened to other PRs and there are some active ones that point to `new-design` too. (excluding the ui components)

**Comment by ajmnz** [comment]
https://github.com/benawad/dogehouse/pull/662, https://github.com/benawad/dogehouse/pull/651

**Comment by nadirabbas** [comment]
These two should also go into `staging` @ajmnz

**Comment by benawad** [comment]
basically if they touch `kibbeh` it should go into `new-design` if they touch `kofta` or other packages it should go into staging

**Comment by nadirabbas** [comment]
@benawad the PRs @ajmnz mentioned were about `kofta`, they mistakenly got merged into `new-design`

**Comment by benawad** [comment]
yeah no worries, I've did the same a couple times 😅

**Comment by benawad** [comment]
I went back a fixed the second one, and the first one is fine to go into `new-design` because its just a readme change

**Pull request merged**
