### PR TITLE
(kofta) Lot's of polish, twemojis and more!

### PR DESCRIPTION
**Pull request by f1shy-dev**
Hello! This pull request adds *a lot* of polish to kofta, and fixes multiple bugs, mainly to do with languages and emojis. (Sorry for the super trash names for the commits on the first few commits) Here's a list of changes:
# This PR is dead, I'm just using it to see what I need to do in separate PRs!

*Modal PR*
- [x] Move Settings into Modal
- [x] Make User Profile into Modal

*Twemoji PR*
- [ ] Replace all Emojis with Twemoji
- [ ] Add AutoComplete for Emotes

*Language Picker PR*
- [ ] Move Language Picker to Settings
- [x] Redo Language Picker for Twemoji Flags

**Related Issues**
#1427 #1330 #1412

### CODE REVIEW

**Comment by samarmohan** [comment]
You may want to separate this into multiple prs to make it easier for reviewers.

**Comment by vi241** [comment]
Yes, this pull request changes a lot, it will be better to just split it into smaller ones

**Comment by goldyydev** [comment]
@vishy-dev you might want to change the emoji kit in emoji-mart to Twemoji too.

**Comment by f1shy-dev** [comment]
Yeah I'll do that too.

**Comment by f1shy-dev** [comment]
Oh god, i ran some lint and i18 and now there's so much stuff that overlaps/conflicts

**Review by f1shy-dev — COMMENTED** [review]
This commit is mainly linting and adds the settings modal. (Sorry if this is a pain for reviewers, I didn't know that linting would do all this).

**Comment by f1shy-dev** [comment]
> Yes, this pull request changes a lot, it will be better to just split it into smaller ones

Um problem, I can’t really do that now that I accidentally committed all the ESLint changes. Should this just be reviewed in one go, ignoring the ESLint commit (or I could say what was actually changed in the commit with ESLint and that could be manually checked).

**Comment by f1shy-dev** [comment]
Still making these changes, just going to individually PR them and fix code stuff.

**Comment by vi241** [comment]
Next time split the pr

**Comment by vi241** [comment]
because 10 small pr are easier to check than 1 big one

**Comment by f1shy-dev** [comment]
Yeah I’m gonna split it and fix the really bad commit history.

**Comment by HarrisonMayotte** [comment]
@vishy-dev has the autocomplete for emojis already been PR'd separately?

**Pull request closed without merging**
