### PR TITLE
user bio: linkify, retain indentation

### PR DESCRIPTION
**Pull request by nadirabbas**
| Before  | After |
| ------------- | ------------- |
| image| image|

### CODE REVIEW

**Comment by nadirabbas** [comment]
@ajmnz

**Comment by ajmnz** [comment]
Why? So your bio looks good?😂

**Comment by nadirabbas** [comment]
yeah, and so people's bio looks good too. lol

**Comment by nadirabbas** [comment]
@ajmnz  it just adds a couple of classes to keep the indentation that the user added. and linkifies the bio. Merge it if it's okay, otherwise I can change anything if needed.

**Comment by ajmnz** [comment]
I want it to be centered for now. We might come back to it later, but definitely not by keeping the profile pic and follow button centered and the rest left-aligned.

**Pull request closed without merging**
