### PR TITLE
feat(EditProfileModal): discord avatar urls

### LINKED ISSUE #2516: Possibly incorrect label
**Describe the bug**
Label reading "GitHub/Twitter avatar URL" where I assume discord should be included too. I assume that this was forgotten when adding Discord auth back into DogeHouse.

**To Reproduce**
1. Go to the account page from dogehouse.tv/dash
2. Click "edit profile"
3. The incorrect label should now be on screen

**Expected behavior**
Expected label to read "GitHub/Twitter/Discord avatar URL"

**Screenshots**
Screenshot 2021-05-03 at 07 38 48

**What device are you on?**
2011 Macbook Pro --> macOS 10.15.7 --> Safari

### LINKED ISSUE #2534: Avatar URL is always "invalid"
**Describe the bug**
The avatar url is always invalid even if I don't change it. Also, it wont accept any URL as an image

**To Reproduce**
1. Go to your profile page
2. Click on 'edit'
3. Do not change anything
4. Click Save or whatever it says

**Expected behavior**
Just save the changes and close

**Screenshots**

Screenshot 2021-05-03 195513

Screenshot 2021-05-03 195523

Screenshot 2021-05-03 195533

**What device are you on?**

Windows 10 pro for workstations desktop using Opera(chromium)

### PR DESCRIPTION
**Pull request by nadirabbas**
- fixes #2534 
- fixes #2516

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
use the proper capitalization for github (GitHub)

**Comment by benawad** [comment]
add a test case for this

**Comment by amitojsingh366** [comment]
closes #2516

**Comment by TheOtterlord** [comment]
@nadir Please update your commit message to pass the test

**Comment by TheOtterlord** [comment]
@nadirabbas please also update the commit message to pass the test

**Pull request merged**
