### PR TITLE
Translated "Discord" to the selected language for most languages

### PR DESCRIPTION
**Pull request by MattLawz**
Fix for issue #745 and #705

**This is only for some languages, I didn't wanna touch about 5 because I wasn't familiar with them.**

### CODE REVIEW

**Comment by nadirabbas** [comment]
Why would you translate Discord? It is a name...

**Comment by prokopschield** [comment]
Is this a joke?

Discord is an app....

**Comment by MattLawz** [comment]
> Why would you translate Discord? It is a name...

Well from what I know in some other countries, "discord" is in their language so they might not understand it because discord has the name to the location.

**Comment by nadirabbas** [comment]
@prokopschield Discord is the name of an app, isn't it? Would you translate Dogehouse to Kuttaghar in urdu?

**Comment by prokopschield** [comment]
> > Why would you translate Discord? It is a name...
> 
> Well from what I know in some other countries, "discord" is in their language so they might not understand it because discord has the name to the location.

Discord, as in, the app, is always Discord, in every language.

**Comment by nadirabbas** [comment]
discord is an English word too, so that's why it has translations. but in the case of Discord is a proper noun.

**Comment by nadirabbas** [comment]
so we dont need to translate Discord as far as I know.

**Comment by MattLawz** [comment]
> @prokopschield Discord is the name of an app, isn't it? Would you translate Dogehouse to Kuttaghar in urdu?

I guess to

> so we dont need to translate Discord as far as I know.

Your right, you may close the PR.

**Pull request closed without merging**
