### PR TITLE
fix(kibbeh): add more Linux platforms to download

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by ghost** [comment]
image

**Review by willdoescode — APPROVED** [review]

**Review by overlisted — APPROVED** [review]
ugly but ok

**Comment by ghost** [comment]
*Always has been*

**Comment by ghost** [comment]
I will try to fix the downloads page in this PR from now on. Kinda hate changing the scope of a PR but meh

**Comment by BronzW** [comment]
You could take inspiration from the discord download page
image

**Comment by ghost** [comment]
That's what I'm planning to do. I'll most likely make a dropdown for Linux downloads instead of having a bazillion buttons for each way of packaging.

**Comment by ghost** [comment]
nvm will do that in a later pr. pls merge

**Comment by overlisted** [comment]
fix the eslint error please

**Comment by samarmohan** [comment]
> You could take inspiration from the discord download page
> image

@ajmnz has to approve new design thingies.

**Comment by ajmnz** [comment]
> @ajmnz has to approve new design thingies.

I didn't even get to design it, so no worries for now

**Comment by amitojsingh366** [comment]
> You could take inspiration from the discord download page
> image

no, don't do that. we will redesign when @ajmnz comes up with a design for this

**Comment by ghost** [comment]
> 
> 
> fix the eslint error please
how the hell did that happen

**Comment by laurens-vrh** [comment]
Maybe just add a dropdown for all the Linux ones for now, and improve the design later ?

Edit: minor detail; but when you hover over the Dogehouse logo, there's no cursor pointer

**Comment by ghost** [comment]
don't feel like doing that atm, but i'll do it in another pr

**Pull request merged**
