### PR TITLE
Actually ignore the .idea folder

### PR DESCRIPTION
**Pull request by samarmohan**
This did not work otherwise.

### CODE REVIEW

**Comment by overlisted** [comment]
keep `*/.idea`

**Comment by amitojsingh366** [comment]
> 
> 
> you should keep `*/.idea`

**Comment by amitojsingh366** [comment]
> 
> 
> you should keep `*/.idea`

@overlisted let's close this then?

**Comment by samarmohan** [comment]
It didn’t work otherwise. I tested it.

**Comment by HarrisonMayotte** [comment]
Add both lines.

**Comment by samarmohan** [comment]
I'll do that, the OG line ignored `.idea` folders in subfolders, not the root,

**Comment by samarmohan** [comment]
You may need a `/` after `*/.idea`.

**Comment by samarmohan** [comment]
> you should keep `*/.idea`

That doesn't work while my change works so there is no point in keeping that.
My change also ignores all `idea` folders in subdirs

**Comment by HarrisonMayotte** [comment]
It does work- just not for the way you were using it. If someone opened a specific subfolder with the IDE that generates the .idea folder, it'll generate that in the subfolder, which is what the line there is for. ***Even if it didn't*** (which it does), one extra line for a "just in case" doesn't hurt.

**Comment by samarmohan** [comment]
Ok, I’ll add it!

**Review by overlisted — APPROVED** [review]

**Pull request merged**
