### PR TITLE
More stuff in kebab

### PR DESCRIPTION
**Pull request by overlisted**
- Better READMEs
- Cleaned up the examples
- Fixed a couple of audio related bugs and warnings
- Add the currently played user ID to consumer player parameters

Mic producing is still broken; don't merge if you need it

### CODE REVIEW

**Comment by nadirabbas** [comment]
How will the `mediasoup-client` work for node? It is made for the browser. You could look into using `simple-peer` along with `wrtc` packages, which gives a backend implementation of WebRTC.

**Comment by overlisted** [comment]
it won't work in node, im going to add a ffmpeg-based implementation later

**Comment by nadirabbas** [comment]
`wrtc` is a WebRTC implementation for `node`

**Comment by overlisted** [comment]
i know

**Pull request merged**
