### PR TITLE
Added more languages and simplified language names

### PR DESCRIPTION
**Pull request by manaskhandelwal**
#### Added more languages. All language labels are in alphabetical order. All language codes (except some) follow [`ISO 639-1`](http://www.mathguide.de/info/tools/languagecode.html).

I will keep adding new languages as they added.

###### Current Languages Count: 36 😲

### CODE REVIEW

**Comment by manaskhandelwal** [comment]
@nadirabbas Should I remove the `kofta/yarn.lock` and `kofta/package-lock.json` from my pull request. I thought they were in `.gitignore`

**Comment by nadirabbas** [comment]
yeah `yarn.lock` should be removed completely. and you can remove `package-lock` if you haven't installed anything.

**Comment by manaskhandelwal** [comment]
@nadirabbas so should I add `kofta/yarn.lock` and `kofta/package-lock.json` in `.gitignore` also and should I make a new pull request and close this one or I can do that with this?

**Comment by nadirabbas** [comment]
no, don't add in `gitignore`, just reset those files to staging and commit in the same PR

**Comment by nadirabbas** [comment]
`git reset package-lock.json ben/staging`

**Pull request closed without merging**
