### PR TITLE
Translated phrases from English to Arabic

### PR DESCRIPTION
**Pull request by charafmrah**
When I visited the website and changed the language to Arabic, I found that there were many phrases that were still showing in English. I decided to help out my Arab folks and translate some words for them.

### CODE REVIEW

**Comment by nadirabbas** [comment]
Thank you 🙏

**Comment by ajmnz** [comment]
Please create another PR where you don't change **1,428** files.

**Comment by charafmrah** [comment]
> 
> 
> Please create another PR where you don't change **1,428** files.

This is my first time contributing to another project so sorry for that. Do you have a good resource on how to prevent that? I cloned the repository so most of the changes were done automatically.

**Comment by ghost** [comment]
There's a couple of issues with this PR, I will tell you what I found wrong:
1. make a different branch for your changes. don't make your changes right into **staging**, make a branch from staging, and do your changes there. that way it isn't that much of a mess. (As an example, you make a new branch from staging, called something like "patch-1".)
2. Don't change all files. Did you reformat the entire project from LF to CRLF?

**Comment by charafmrah** [comment]
> 
> 
> There's a couple of issues with this PR, I will tell you what I found wrong:
> 
>     1. make a different branch for your changes. don't make your changes right into **staging**, make a branch from staging, and do your changes there. that way it isn't that much of a mess. (As an example, you make a new branch from staging, called something like "patch-1".)
> 
>     2. Don't change all files. Did you reformat the entire project from LF to CRLF?

Noted, thank you!

**Comment by nadirabbas** [comment]
@Odyssey346 Why is `staging` a problem when he's pushing to his fork?

**Comment by ghost** [comment]
I've seen most people just make a new branch just for their changes, and it's just way cleaner.

**Comment by ghost** [comment]
It's also in [CONTRIBUTING.md](https://github.com/benawad/dogehouse/blob/staging/CONTRIBUTING.md), it clearly says you should be doing seperate branches for your changes.

**Comment by charafmrah** [comment]
I created a new pull request with only 1 file changed, hope that one is good.

**Pull request closed without merging**
