### PR TITLE
feat(kousa): order room search by numPeopleInside and user search by numFollowers

### PR DESCRIPTION
**Pull request by amitojsingh366**
- order room search by numPeopleInside and user search by numFollowers

### CODE REVIEW

**Review by benawad — CHANGES_REQUESTED** [review]
write a test

**Comment by amitojsingh366** [comment]
> 
> 
> write a test

i believe there are already tests for search aren't they?

**Comment by benawad** [comment]
not verifying that your order by works

**Comment by amitojsingh366** [comment]
> 
> 
> not verifying that your order by works

done

**Pull request merged**
