### PR TITLE
Added simplified language names and removed undefined class

### PR DESCRIPTION
**Pull request by manaskhandelwal**
#### Added more languages. All language labels are in alphabetical order. All language codes (except some) follow [`ISO 639-1`](http://www.mathguide.de/info/tools/languagecode.html).

I will keep adding new languages as they added.

###### Current Languages Count: 37 😲

***

Removed the `undefined` class from Avatar.

### CODE REVIEW

**Comment by manaskhandelwal** [comment]
@nadirabbas I messed some things up 😩 so I am making a new request and closed the old one.

**Comment by nadirabbas** [comment]
why did you remove `circle` from `Avatar.tsx`?

**Comment by manaskhandelwal** [comment]
> why did you remove `circle` from `Avatar.tsx`?

@nadirabbas The profile is circle everywhere (class `rounded-full`) but on the profile page (`/me`) and the `profile modal` it is not a perfect circle (class `rounded-3xl`). So I thought we should make it consistent every where. If you say I will add the `circle` prop and make the components with the circle prop `rounded-full` so it is consistent through the website.

**Comment by nadirabbas** [comment]
@manaskhandelwal i think having it slightly squared is intended, i think its better if we re add `circle` prop.

**Comment by ermalsh** [comment]
Fix conflicts due to file naming changes since the greek translations were updated and emoji flags added.

**Comment by augielavin** [comment]
How dum rite

**Comment by manaskhandelwal** [comment]
@nadirabbas @ermalsh I have done it, plz check.

**Comment by nadirabbas** [comment]
more conflicts XD

**Comment by nadirabbas** [comment]
we already have language labels in the site, what does this PR add?

**Pull request closed without merging**
