### PR TITLE
Resized Blaze emote to 28x28

### PR DESCRIPTION
**Pull request by slightknack**
Old PR seemed to have gotten merged prematurely. I've resized the emote to 28x28 as requested.

### CODE REVIEW

**Comment by slightknack** [comment]
I will say that's the fastest merge I've seen.

**Comment by vi241** [comment]
the last one was merged, and it wasn't 28x28

**Comment by vi241** [comment]
so all i needed to check was if you resized

**Comment by vi241** [comment]
and you did, so I merged

**Comment by slightknack** [comment]
not questioning the reasoning, just pointing out the speed :smile:

**Comment by vi241** [comment]
k

**Pull request merged**
