### PR TITLE
(feat): Customize nprogress

### PR DESCRIPTION
**Pull request by sohank1**
nprogress now uses same color as buttons

### CODE REVIEW

**Comment by ajmnz** [comment]
Set it to `primary-700` or `primary-600` instead of the accent and fix your commits

**Comment by sohank1** [comment]
How could I fix the commits?

**Comment by ajmnz** [comment]
> How could I fix the commits?

@dk-raw ^

**Comment by dk-raw** [comment]
I won't 🦊 it

**Comment by dk-raw** [comment]
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

**Comment by sohank1** [comment]
I will just make a new pr because I don't have to project cloned so I can't delete commits

**Pull request closed without merging**
