### PR TITLE
Hyper hype beast refactoring 6

### PR DESCRIPTION
**Pull request by arthurysong**
@ityonemo same refactoring done in #554 (hhb-4) applied to Rooms and UserBlocks modules :smiley:

### CODE REVIEW

**Comment by ityonemo** [comment]
@benawad this looks good to me

**Comment by ajmnz** [comment]
Should be rebased to `staging`, shouldn't it?

**Comment by benawad** [comment]
yeah @arthurysong can you set this to staging

**Comment by arthurysong** [comment]
@benawad oh yeah mb, i set the base to staging :+1:

**Pull request merged**
