### PR TITLE
#1180 

### PR DESCRIPTION
**Pull request by ThatOneHidde**
#1180

### CODE REVIEW

**Comment by nadirabbas** [comment]
reset lockfile

**Comment by ThatOneHidde** [comment]
is it ok now?

**Comment by benawad** [comment]
can you add a pic of what the new change looks like

**Comment by ThatOneHidde** [comment]
Its just the hover effect to make it feel snappy 😂
i used the colors alrady used for hover.
7ho4Ojo
w6MO74e

**Pull request merged**
