### PR TITLE
shorten room-names in UI fixing #135 #136 #139

### PR DESCRIPTION
**Pull request by MrMalloc**

### CODE REVIEW

**Comment by MrMalloc** [comment]
Limiting the number of maximum lines of room-names on the Home page with
``` css
display: -webkit-box;  
-webkit-line-clamp: /*linecount*/; 
-webkit-box-orient: vertical;
```
 should be considered

**Comment by benawad** [comment]
lets clamp 3 lines for now

**Comment by MrMalloc** [comment]
@benawad Do you add the 3 lines when merging the PR or should I update the PR?

**Comment by benawad** [comment]
Can you add it to this pr

**Comment by Playit3110** [comment]
I hope we can fix it. :)

**Comment by MrMalloc** [comment]
Ok we are now breaking long words into multiple lines and clamp them if they exceed 3 lines.

**Pull request merged**
