### PR TITLE
Polish locale

### PR DESCRIPTION
**Pull request by miroslawmajka**
Hi Ben, I've started translating `kofta` into Polish. 

Getting sleepy after a long week so expect another PR tomorrow with the remaining lines.

Good job with this project!

### CODE REVIEW

**Comment by nadirabbas** [comment]
may be we can merge tomorrow when all changes are done ?😅

**Comment by benawad** [comment]
switch to `staging` branch

**Comment by miroslawmajka** [comment]
Yeah, no problem, it can wait til all lines are ready 😴

**Comment by nadirabbas** [comment]
please pull from `staging` instead of `new-design`, otherwise `kibbeh` is gonna go into `staging`

**Pull request closed without merging**
