### PR TITLE
deploy using docker compose for dev and prod.

### LINKED ISSUE #101: Containerize Dogehouse
## About the Problem

Installing dependencies for the backend (Elxir API / Voice/WSS server) and frontend (React webapp / Puppeteer shenanigans AKA UI Tests and Lighthouse checks) is a mess and may cause dependency hell if left unmanged, and running them one-by-one can be also an distater.

## Solution and To-Dos

* [x] Make an `docker-compose.yml` file in the root directory that includes each subdirectiry's Dockerfiles required for running the instance + database backend.
* [x] Create an `Dockerfile` on each folder in the Dogehouse monorepo.

### PR DESCRIPTION
**Pull request by zaida04**
> ## ⚠️ Help is needed with this PR

closes https://github.com/benawad/dogehouse/issues/101
superceeds https://github.com/benawad/dogehouse/pull/118

# Why this PR over the above linked one?
This PR adds different environments for local development and for production environment, effectively creating a separation between the two environments.

This PR provides a very simple interface for "up'ing" the docker compose files. `./run.sh local up -d --build` and `./run.sh prod up -d --build`

# Current Status:
- **adminer:** ✅
- **postgres:** ✅
- **rabbitmq:** ✅
- **kousa:** ✅ 
- **shawarma:** ✅ 
- **kofta:** ✅ 

# TO:DO
- write .md guide on how to deploy with the docker compose environments.
- ensure the services start up in a specific order (**Note: depends_on only waits for the container to START not for the actual service within to be ready, resulting in the current issue of having services like shwarma connecting to a rabbitmq instance that isn't ready yet, resulting in it refusing the connection.**)

---

<details><summary>Context for this PR:</summary>

image
image

</details>

### CODE REVIEW

**Comment by JacobGo** [comment]
Hi there, I spent some time getting this docker-compose working locally. 

For shawarma, the reason it's failing with 401 is because it's trying to log in with the default `guest` log in. To fix this provide a `RABBITMQ_URL` with the correct amqp url (or alternatively change `RABBITMQ_DEFAULT_USER` and  `RABBITMQ_DEFAULT_USER` both to `guest`.

For kofta, the issue came from the Dockerfile. The user `node` does not have permission in the frontend directory which causes that error. Additionally, `NODE_ENV production` will throw a React refresh runtime error when we run the dev server. To fix you can just remove those two lines from the Dockerfile. Additionally, for running locally if you actually want to make use of the hot reloading it's nice to mount the directory:
```
volumes:
  - './kofta:/usr/src/frontend'
```

Your networking setup wasn't working for me, so I instead ran all the services off the default docker compose network and opened just kofta and kousa ports to connect over localhost. Note that this changes the database and message broker URLs to the name of the service instead of localhost.

Still working on a solution for the order of services. Postgres and RabbitMQ need to come up before everything else. For now I've been running `docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d postgres rabbitmq`, wait for a bit, then bring up the other services.

Here's [my commit](https://github.com/JacobGo/dogehouse/commit/ab148832cdcf816a4f8a92ce82ad309cc5f879a1) summarizing the above changes, feel free to incorporate the commit into your branch.

**Comment by zaida04** [comment]
@JacobGo Hello! I went ahead and integrated the commit into my branch. Thank you so much for your help! I really appreciate it.

**Comment by zaida04** [comment]
Alright, so now the only error left is when building Kousa. At the 7th build step in the Dockerfile (`RUN mix do deps.get, deps.compile`), one of the dependencies has an issue being compiled. I am not familiar with Elixir at all, so perhaps someone more proficient in it can lend me a hand to try to debug this.

```
...other dependencies being built
#16 11.34 Generated connection app
#16 12.12 ===> OTP release 22.1 or later is required. Version in use: 22.0.7
#16 12.13 ==> kousa
#16 12.13 ** (Mix) Could not compile dependency :credentials_obfuscation, "/root/.mix/rebar3 bare compile --paths="/app/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile credentials_obfuscation", update it with "mix deps.update credentials_obfuscation" or clean it with "mix deps.clean credentials_obfuscation"
------
executor failed running [/bin/sh -c mix do deps.get, deps.compile]: exit code: 1
ERROR: Service 'kousa' failed to build
```

**Comment by JacobGo** [comment]
Hmm, kousa is building fine for me. Can you try a clean build? 

`docker-compose -f docker-compose.yml -f docker-compose.local.yml build --no-cache kousa`

**Comment by zaida04** [comment]
Same output. Tested on both WSL Ubuntu and on Windows 10 Pro with clean clones

**Comment by jamesql** [comment]
got this error earlier trying to build my local Kousa,
You need to upgrade your erlang to => 22.1

@zaida04

**Comment by zaida04** [comment]
I'm unsure of how to do that within the Dockerfile itself, since the problem is only occurring when I build *in* the Dockerfile itself. It is perfectly fine on my local machine. I should have been clearer when I meant that when I tested it on WSL Ubuntu and Windows 10 Pro, I meant that I attempted to build the docker container on both platforms and encountered that error during the build.

**Comment by Choongkyu** [comment]
has anyone been able to run a containerized version of shawarma, the voice server with no issues?  I'm seeing this diff and it looks like no ports are forwarded. While I can run the voice server and see activity being logged while being connected to the message broker and kousa, the backend, and I'm able too see the "voice ring" around each speaker move when speech is detected, the audio itself isn't coming through. I tried porting the ports by adding `"40000-49999:40000-49999"` under the voice server part of my compose file as well as tried setting `network_mode` to `host` to eliminate the need for adding port bindings as well as setting the webrtc listening ip from `127.0.0.1` to `0.0.0.0`, I'm having the same issue. Thanks!

**Comment by jeroondeg** [comment]
hello

**Comment by amitojsingh366** [comment]
What is the status of this PR? are you still working on this? also is [`.devcontainer`](https://github.com/benawad/dogehouse/tree/staging/.devcontainer) a valid alternative for this?

**Comment by zaida04** [comment]
I'm currently at a roadblock at this PR because of https://github.com/benawad/dogehouse/pull/563#issuecomment-798792943. However some people say they aren't able to replicate this on their systems, so I'm awaiting either a solution to this or someone to confirm that it's just a problem on my end (since I've tested on both WSL and Windows with fully updated Erlang versions, I'm thinking it might be an actual issue).

Looking at devcontainer, it fulfills a different purpose than what this PR is for. While this PR also provides a dev docker-compose file for testing, it's main goal is to provide a production ready docker compose setup, which isn't there.

**Comment by amitojsingh366** [comment]
> I'm currently at a roadblock at this PR because of [#563 (comment)](https://github.com/benawad/dogehouse/pull/563#issuecomment-798792943). However some people say they aren't able to replicate this on their systems, so I'm awaiting either a solution to this or someone to confirm that it's just a problem on my end (since I've tested on both WSL and Windows with fully updated Erlang versions, I'm thinking it might be an actual issue).
> 
> Looking at devcontainer, it fulfills a different purpose than what this PR is for. While this PR also provides a dev docker-compose file for testing, it's main goal is to provide a production ready docker compose setup, which isn't there.

Sounds good! so any eta by when this is gonna be ready?

**Comment by zaida04** [comment]
Well, as I said in the linked comment, I'm not familiar with elixir in any capacity, so I can't really debug this issue that well (I tried), so until I'm able to get ahold of someone who is more familiar with elixir/someone else is able to debug it, I can't really finish this PR. 

So to answer your question, the eta is: `:shrug:`

**Comment by ParthSatodiya** [comment]
@zaida04 

I am not familiar with elixir, but I got the similar error with docker-compose local config (`docker-compose -f docker-compose.yml -f docker-compose.local.yml build kousa`).

But then when I tried the **kousa** Dockerfile pushed in latest staging branch by [this commit](https://github.com/benawad/dogehouse/commit/1ebe39e2474cbafde76ef2fe75cf9dc77f408646#diff-ba1ea00371bd886180d5f5e95f8041a43c6588b6c4e18a2fd9b4ba0a29511f47), it built the image successfully.
So yaa, if you use the latest _kousa/Dockerfile_ available in staging, it should solve the  issue.

**Comment by zaida04** [comment]
@ParthSatodiya you were correct, the docker builds do infact work on the latest version! Thank you so much, and with this all the docker builds successfully build. I'll go ahead and mark this PR as ready for review.

**Comment by benawad** [comment]
does this work now?

**Comment by vi241** [comment]
this is a very old pr

**Comment by zaida04** [comment]
> does this work now?

It does work on my end, yes.

**Comment by BronzW** [comment]
If conflicts are fixed then this would be able to merge I guess.

**Comment by overlisted** [comment]
are you going to finish the stuff in the todo section

**Comment by vi241** [comment]
**conflicts**

**Comment by zaida04** [comment]
> If conflicts are fixed then this would be able to merge I guess.

Resolved.



> are you going to finish the stuff in the todo section

As for the second bullet point in the TO:DO section, I don't think I'll be able to accomplish it. However, I will be able to accomplish the first point.

**Comment by amitojsingh366** [comment]
@zaida04 @overlisted @ofsho is this ready to merge?

**Comment by amitojsingh366** [comment]
oh wait, it isn't @zaida04 your commit messages need to follow the conventional commit standard. use `yarn commit` or `yarn commit:signed` to generate your commit msgs, but you've already generated them so you'll have to rename them the hard way. *(you can ping me on discord if you need help with renaming, `Amitoj366#6020` is my discord)*

**Comment by overlisted** [comment]
the commits were made before ben started enforcing angular's standard so i think we can keep them

**Comment by amitojsingh366** [comment]
> 
> 
> the commits were made before ben started enforcing angular's standard so i think we can keep them

this is a major change and if what ben says is correct *(about auto generating change logs)* then this needs to be in that log. also its not that hard to rename commits, i can help them if they dm me

**Comment by Choongkyu** [comment]
great job! Is it just me or is the audio still not coming through when running `docker-compose.local.yml`?

**Pull request merged**
