### PR TITLE
add translation to latvian

### PR DESCRIPTION
**Pull request by xanthopsia**
Added translation to latvian

### CODE REVIEW

**Comment by MadanBhandari** [comment]
@xanthopsia also add this language  at `LanguageSelector` component

**Comment by ermalsh** [comment]
Please add to `LanguageSelector.tsx`, and then I'll approve.

**Review by MadanBhandari — APPROVED** [review]

**Comment by ermalsh** [comment]
@xanthopsia Please remove the swap file created by the VIM `kofta/src/app/components/.LanguageSelector.tsx.swp `

**Comment by xanthopsia** [comment]
> @xanthopsia Please remove the swap file created by the VIM `kofta/src/app/components/.LanguageSelector.tsx.swp `

I don't see the .swp file?

**Comment by ermalsh** [comment]
> > @xanthopsia Please remove the swap file created by the VIM `kofta/src/app/components/.LanguageSelector.tsx.swp `
> 
> I don't see the .swp file?

https://stackoverflow.com/a/13361874/3838600

**Pull request merged**
