### PR TITLE
Added margin bottom

### LINKED ISSUE #738: The last row of listeners are not visible
**Describe the bug**
Cannot see the last row of attendees

**To Reproduce**
1. Go to a room
2. In the listeners sections
3. Scroll down to bottom
4. The last row of listeners are not visible

**Expected behavior**
A little padding at the bottom so that the last row is clearly visible

**Screenshots**
image

**What device are you on?**
Device Lenovo Ideapad 
Browser: Mozilla Firefox

**Additional context**

### PR DESCRIPTION
**Pull request by manaskhandelwal**
Close #738 

Added `mb-12` to the container div of *speakers* and *listeners*.

**Bug Details:**
* Mozilla:

  mozbug

* Chrome:
 
  chromebug

###### If the description is less/improper plz let me know so I will better write a better one next time.

### CODE REVIEW

**Comment by ajmnz** [comment]
Could you change the base to `staging`?

**Comment by manaskhandelwal** [comment]
@ajmnz I did it.

**Comment by manaskhandelwal** [comment]
@ajmnz Did I do something wrong?

**Comment by nadirabbas** [comment]
could you pull from `staging` instead of `new-design`. currently it will merge `new-design` into `staging`

**Pull request closed without merging**
