### PR TITLE
feat(kofta): added translation to the language "Toki Pona" in the "tp…

### PR DESCRIPTION
**Pull request by GiggioG**
…" locale

feat #1642

Toki Pona is a philosophical artistic constructed language (or philosophical artlang) known for its small vocabulary. It was created by Canadian linguist and translator Sonja Lang for the purpose of simplifying thoughts and communication. - [Wikipedia](https://en.wikipedia.org/wiki/Toki_Pona)

### CODE REVIEW

**Comment by amitojsingh366** [comment]
according to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) the `tp` language code is "Unassigned". so im not sure we can use this or not... I'll confirm this with others till then why not go and add the same translation to `kibbeh`?

**Comment by amitojsingh366** [comment]
> 
> 
> according to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) the `tp` language code is "Unassigned". so im not sure we can use this or not... I'll confirm this with others till then why not go and add the same translation to `kibbeh`?

@benawad is this allowed? assigning a custom language to an unassigned code i mean.

**Comment by GiggioG** [comment]
it can always be changed, i just did tp because it was unassigned
and bruh, forgot about the kibbeh, ill start by seeing what can be copied over

**Comment by GiggioG** [comment]
Did the kibbeh locale, didn't find the kibbeh version of `kofta/src/app/components/LanguageSelector.tsx` and the "Launguage" button on `next.dogehouse.tv` does nothing, so I didn't add the locale anywhere.

**Comment by amitojsingh366** [comment]
ok seems good. lemme ask the others if using `tp` code is fine

**Pull request merged**
