### PR TITLE
Unban new admin from chat

### LINKED ISSUE #526: admin can be banned
as this happened with @nadirabbas  can you describe this @nadirabbas ?

### PR DESCRIPTION
**Pull request by melnary**
Fixes #526.

If a user has previously been banned from chat and becomes an owner, this change makes sure that the new admin becomes unbanned.

This adds a new event `chat_user_unbanned`, but does not add any new features, due to the redesign not being finished yet.

### CODE REVIEW

**Comment by melnary** [comment]
Noticing now that this overlaps with #1525.
That PR doesn't actually handle the admin being banned case but it does implement the same events as this.

**Comment by wes337** [comment]
Hmm, so if yours is merged first I could just update my PR to only implement that `wsend({"unban_from_room_chat" ...` button in the profile modal?

**Comment by melnary** [comment]
> Hmm, so if yours is merged first I could just update my PR to only implement that `wsend({"unban_from_room_chat" ...` button in the profile modal?

I think so, pretty sure we only have a conflict on the `:unban_user` cast handler in Onion.RoomChat, where I also check whether a user has been banned first before sending the messages, but other than that it should merge fine.

**Review by wes337 — APPROVED** [review]

**Comment by goldyydev** [comment]
@benawad going to need you to review this and #1525

**Comment by BronzW** [comment]
Status on this PR?

**Comment by vi241** [comment]
??

**Comment by nadirabbas** [comment]
@benawad what to do about this one?

**Comment by melnary** [comment]
Can someone check whether this is still a thing that could happen? Otherwise this should be closed.

**Comment by melnary** [comment]
Ah, the issue has been closed, I'll close this too then.

**Pull request closed without merging**
