### PR TITLE
adding searchUserPage css

### PR DESCRIPTION
**Pull request by logark12**

### CODE REVIEW

**Comment by tejxv** [comment]
this is not required at the moment


see this https://github.com/benawad/dogehouse/issues/1117#issuecomment-800535736

**Comment by logark12** [comment]
ok bro i didn't  see  the comment

**Comment by logark12** [comment]
okay bro i didn't see it

**Comment by tejxv** [comment]
yeah it's fine, save it for later maybe

**Comment by logark12** [comment]
ok

**Comment by tejxv** [comment]
same with #1127

**Comment by logark12** [comment]
oh ok

**Pull request closed without merging**
