### PR TITLE
Update Swedish translation.json

### PR DESCRIPTION
**Pull request by BronzW**
- Fixed grammar to match language #1491 
- Added missing translations
- Other small fixes

### CODE REVIEW

**Comment by ghost** [comment]
I'm not Swedish, but shouldn't "errors" be feil? It's like that in Norwegian, and Norwegian is a bit similar to Swedish.

**Comment by amitojsingh366** [comment]
> 
> 
> I'm not Swedish, but shouldn't "errors" be feil? It's like that in Norwegian, and Norwegian is a bit similar to Swedish.

@Odyssey346 @BronzW is this solved?

**Comment by BronzW** [comment]
I edited it from github, so there is no fork of it. I can't edit it.

**Comment by amitojsingh366** [comment]
> 
> 
> I edited it from github, so there is no fork of it. I can't edit it.

So does this mean it's wrong translations? Can i close this?

**Comment by HarrisonMayotte** [comment]
It says that it is in BronzW:patch-2 so I'm not sure if it could be edited there.

**Comment by BronzW** [comment]
You should normally be able to click on it, but it's just grey, not blue.
image

**Comment by BronzW** [comment]
Worst case I will just create a new pull request with the changes

**Comment by ermalsh** [comment]
JSON valid, looks good.

**Pull request merged**
