### PR TITLE
Resolves #572 - Hide/Show Listeners

### LINKED ISSUE #572: Minimize Listeners
Making it possible to minimize the listeners as listeners grow in number.

### PR DESCRIPTION
**Pull request by wes337**
If a room has more than 50 listeners, we will show a button which can be used to hide/show the listeners. Still needs a better design. Resolves #572

### CODE REVIEW

**Comment by 11ma** [comment]
> If a room has more than 50 listeners, we will show a button which can be used to hide/show the listeners. Still needs a better design. Resolves #572 

isn't 50 too much? won't that just make a room page unnecessary long to scroll down?

**Comment by benawad** [comment]
do you have a screen shot of what it looks like?

**Comment by wes337** [comment]
> 
> 
> > If a room has more than 50 listeners, we will show a button which can be used to hide/show the listeners. Still needs a better design. Resolves #572
> 
> isn't 50 too much? won't that just make a room page unnecessary long to scroll down?

It could be, what number do you think is a good amount before we allow the user to hide?

> 
> 
> do you have a screen shot of what it looks like?

Listeners open:
open

Listeners hidden:
closed

**Comment by 11ma** [comment]
noice, thanks for the screenshots, how does 25 sound?

**Comment by benawad** [comment]
I think you should have it still show some listeners, but a show more at the bottom

**Pull request merged**
