### PR TITLE
New folder: kebab!

### PR DESCRIPTION
**Pull request by overlisted**
Kebab is a new, rewritten API client that is going to be used in kibbeh.

- [x] Raw API
- [x] A simple example program
- [x] NPM Package
- [ ] Audio
- [x] TypeScript
- [x] TypeScript types for all DogeHouse entities
- [x] Convenient predefined functions for all API endpoints
- [ ] Convenient DOM-like events for all API events 
- [x] ESLint

### CODE REVIEW

**Comment by MaySoMusician** [comment]
Sorry for interruption, but are you sure you're going to merge this to `new-design` branch? Just in case.

**Comment by overlisted** [comment]
Yes? This is exclusively for the new design

**Comment by MaySoMusician** [comment]
uh that's ok, thx

**Comment by yummyweb** [comment]
I believe currently this is the Dogehouse JS project which is part of Dogegarden.

**Comment by overlisted** [comment]
not anymore lol

**Pull request merged**
