### PR TITLE
Update Dutch translations

### PR DESCRIPTION
**Pull request by jobveldhuis**
Translations are now more in line with recommended Dutch spelling and grammar rules. Also, general improvements to the Dutch translations.

This change implements the following rules of grammar:
- [Compositions should not include spaces](https://onzetaal.nl/taaladvies/samenstelling)
- [Words in titles should minimize the amount of capital letters](https://taaladvies.net/taal/advies/tekst/98/hoofdletters_bij_titels_van_boeken_liedjes_films_ed_algemeen/)

It also includes some translations I believe to be more understandable for users. For instance the change to update the text `toegankelijkheidsrechten` to `benodigde permissies`.

### CODE REVIEW

**Comment by jobveldhuis** [comment]
This PR has not pulled the latest English localization file and, as such, does not add new lines of text that is currently untranslated.

**Comment by vi241** [comment]
first resolve conflicts

**Comment by jobveldhuis** [comment]
There you go, @ofsho. It now also has updated translations for strings that weren't previously translated.

**Comment by vi241** [comment]
ok i will review it

**Review by vi241 — APPROVED** [review]

**Pull request merged**
