### PR TITLE
Implemented the new profile page & Added the banner API to Kousa

### PR DESCRIPTION
**Pull request by goldyydev**
This PR:
- Implements the new profile page
- Fixes some weird bugs with the components
- Needs some new icons (possibly in a future PR [@ajmnz])

🛈 Currently the banners are using the unsplash random api to generate a banner, banners still have to be implemented on the backend (and so do these options)
image

<sub>Have fun reviewing this huge PR!<sub>

### CODE REVIEW

**Review by samarmohan — APPROVED** [review]

**Comment by BronzW** [comment]
I will implement banners to the API, unless someone already did so please don't merge this PR. 
image

**Comment by ajmnz** [comment]
@goldyydev Let me know which icons you need and I'll push them to this pr

**Comment by goldyydev** [comment]
> @goldyydev Let me know which icons you need and I'll push them to this pr

@ajmnz I need the Edit Profile icon

**Comment by dark-elixir-shibe** [comment]
@benawad this PR broke a ton of stuff because it edited one of the migrations in the past, which you should not do.  We gotta stop accepting PRs that fail the elixir test suite.

**Pull request merged**
