### PR TITLE
Patch #2356

### PR DESCRIPTION
**Pull request by Gers2017**
This fixes Issue #2356 ```Chat does not resize properly when changing screen resolutions```. Removing the inline styles that used the position absolute and translate properties to positioning every chat message.
[Breakpoints](https://tailwindcss.com/docs/breakpoints) added on the tailwindcss.config
### Bug
ex2
### This Pull request
ex1
ex3
ex4

### CODE REVIEW

**Comment by amitojsingh366** [comment]
use proper commit messages please *(`yarn commit` or `yarn commit:signed`)*, and pull latest from staging and push

**Comment by ajmnz** [comment]
_I think_ those breakpoints will break way too much stuff that uses `*.-md`, `*.-sm`, etc.

**Comment by Gers2017** [comment]
@ajmnz I can remove them if you want
@amitojsingh366 My bad I made it but I didn't put the same message on the pr

**Comment by ajmnz** [comment]
> @ajmnz I can remove them if you want
> @amitojsingh366 My bad I made it but I didn't put the same message on the pr

Remove them If you can make it work without adding those

**Comment by benawad** [comment]
open a new pr with just the changes you made

**Pull request closed without merging**
