### PR TITLE
Added Romanian translation

### PR DESCRIPTION
**Pull request by slendidev**
Just created a Romanian translation and ran `npm run i18` as told

### CODE REVIEW

**Comment by benawad** [comment]
looks good, but switch to staging branch

**Comment by slendidev** [comment]
I know this sounds dumb, but how do I do it?

**Comment by ellartdev** [comment]
Switch the branch on your computer and then paste the translation.json into locales folder before pushing it to your fork

**Comment by slendidev** [comment]
```
[20:53:17] blyat:kofta git:(new-design*) $ git switch staging
M       kofta/package-lock.json
Switched to branch 'staging'
[20:53:26] blyat:kofta git:(staging*) $ ls public/locales/ro
translation.json
[20:53:37] blyat:kofta git:(staging*) $ git push
fatal: The current branch staging has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin staging

[20:53:51] blyat:kofta git:(staging*) $ git push --set-upstream origin staging
To https://github.com/xslendix/dogehouse
 ! [rejected]        staging -> staging (fetch first)
error: failed to push some refs to 'https://github.com/xslendix/dogehouse'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[20:53:56] blyat:kofta git:(staging*) $ git fetch
[20:54:02] blyat:kofta git:(staging*) $ git push --set-upstream origin staging
To https://github.com/xslendix/dogehouse
 ! [rejected]        staging -> staging (fetch first)
error: failed to push some refs to 'https://github.com/xslendix/dogehouse'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
I hate git

**Comment by slendidev** [comment]
wait i think i figured it out

**Comment by ellartdev** [comment]
> 
> 
> wait i thing i figured it out

that's good to hear, man 👍

**Comment by slendidev** [comment]
I created a new pull request where it is now on the staging branch. Hopefully this will solve the issues.

**Pull request closed without merging**
