### PR TITLE
Updating missing values in Urdu translation

### PR DESCRIPTION
**Pull request by ShahrozTanveer**

### CODE REVIEW

**Review by jamesql — CHANGES_REQUESTED** [review]
Please resolve this request when you are done updating the missing values, thank you for contributing. :)

**Comment by ShahrozTanveer** [comment]
> Please resolve this request when you are done updating the missing values, thank you for contributing. :)

hi @jamesql ,
do i need to change anything?

**Comment by jamesql** [comment]
@ShahrozTanveer 
```"roomDescription": "Description"```
```"makeRoomCreator": "make room admin"```
```     "editProfileModal": {
        "usernameTaken": "username taken",
        "avatarUrlError": "Invalid image",
        "avatarUrlLabel": "Github/Twitter avatar url",
        "displayNameError": "length 2 to 50 characters",
        "displayNameLabel": "Display Name",
        "usernameError": "length 4 to 15 characters and only alphanumeric/underscore",
        "usernameLabel": "Username",
        "bioError": "max length of 160 characters",
        "bioLabel": "Bio"
      },

"viewUser": {
      "editProfile": "پروفائل میں ترمیم کریں",
      "followsYou": "آپ کے پیچھے",
      "followers": "پیروکار",
      "following": "درج ذیل",
      "followHim": "follow",
      "followingHim": "following",
      "copyProfileUrl": "copy profile url",
      "urlCopied": "URL copied to clipboard"
    },
      "allowAll": "Allow all",
      "allowAllConfirm": "Are you sure? This will allow all {{count}} requesting users to speak"
```

**Comment by ShahrozTanveer** [comment]
> @ShahrozTanveer
> `"roomDescription": "Description"`
> `"makeRoomCreator": "make room admin"`
> 
> ```
>         "usernameTaken": "username taken",
>         "avatarUrlError": "Invalid image",
>         "avatarUrlLabel": "Github/Twitter avatar url",
>         "displayNameError": "length 2 to 50 characters",
>         "displayNameLabel": "Display Name",
>         "usernameError": "length 4 to 15 characters and only alphanumeric/underscore",
>         "usernameLabel": "Username",
>         "bioError": "max length of 160 characters",
>         "bioLabel": "Bio"
>       },
> 
> "viewUser": {
>       "editProfile": "پروفائل میں ترمیم کریں",
>       "followsYou": "آپ کے پیچھے",
>       "followers": "پیروکار",
>       "following": "درج ذیل",
>       "followHim": "follow",
>       "followingHim": "following",
>       "copyProfileUrl": "copy profile url",
>       "urlCopied": "URL copied to clipboard"
>     },
>       "allowAll": "Allow all",
>       "allowAllConfirm": "Are you sure? This will allow all {{count}} requesting users to speak"
> ```

okay working on that.
Thanks

**Comment by ShahrozTanveer** [comment]
> @ShahrozTanveer
> `"roomDescription": "Description"`
> `"makeRoomCreator": "make room admin"`
> 
> ```
>         "usernameTaken": "username taken",
>         "avatarUrlError": "Invalid image",
>         "avatarUrlLabel": "Github/Twitter avatar url",
>         "displayNameError": "length 2 to 50 characters",
>         "displayNameLabel": "Display Name",
>         "usernameError": "length 4 to 15 characters and only alphanumeric/underscore",
>         "usernameLabel": "Username",
>         "bioError": "max length of 160 characters",
>         "bioLabel": "Bio"
>       },
> 
> "viewUser": {
>       "editProfile": "پروفائل میں ترمیم کریں",
>       "followsYou": "آپ کے پیچھے",
>       "followers": "پیروکار",
>       "following": "درج ذیل",
>       "followHim": "follow",
>       "followingHim": "following",
>       "copyProfileUrl": "copy profile url",
>       "urlCopied": "URL copied to clipboard"
>     },
>       "allowAll": "Allow all",
>       "allowAllConfirm": "Are you sure? This will allow all {{count}} requesting users to speak"
> ```

@jamesql  done

**Review by jamesql — APPROVED** [review]

**Pull request merged**
