### PR TITLE
feat(kibbeh): created en-CODE language

### PR DESCRIPTION
**Pull request by jaipack17**
i speak code

### CODE REVIEW

**Comment by dk-raw** [comment]
`console.copy()` ?

**Comment by ghost** [comment]
seeeeeeeeeeeeeeems pretty good to me except for the top part.

**Comment by ghost** [comment]
for above, maybe 
navigator.clipboard.writeText() ?

**Comment by jaipack17** [comment]
I ll fix a bunch of stuff the  open another pr. Console.copy() was humor xd

**Pull request closed without merging**
