### PR TITLE
add background color to drop-down to match dark mode UI

### PR DESCRIPTION
**Pull request by leonyanagida**
because Ben loves dark mode

### CODE REVIEW

**Comment by leonyanagida** [comment]
Not sure if I should delete the package-lock.json here

**Comment by benawad** [comment]
does the color of the option text need to change? Also you should keep the package-lock.json as is

**Comment by leonyanagida** [comment]
> does the color of the option text need to change? Also you should keep the package-lock.json as is

No, the option text doesn't need to be changed. Unless you specifically want the text to be a different color.
Thanks, I deleted the package-lock.json file.

**Comment by benawad** [comment]
Yeah, can you put it back

**Comment by leonyanagida** [comment]
> Yeah, can you put it back

Whoops, it's back now.

**Comment by benawad** [comment]
reset it, so there are no package-lock changes in this pr

**Pull request merged**
