### PR TITLE
fix(kibbeh): fix deafen button not showing as listener

### LINKED ISSUE #2271: Deafen button not visible if you're a listener
**Describe the bug**
you can't see the deafen button when you're a listener, but you can still press the deafen keybind.

**To Reproduce**
1. Go in a room
2. Be a listener
3. Don't see the deafen button
4. Press deafen keybind

**Expected behavior**
Deafen button is visible
**Screenshots**

**What device are you on?**
Firefox 87 on openSUSE

**Additional context**
I may try to fix this myself later

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2271

Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by benawad** [comment]
lol you don't see anything odd with that condition?

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
idk what's wrong with it, it works, obviously there's probably a way to optimize it but i can't come up with a way atm

**Comment by dzmitry-vasileuski** [comment]
@Odyssey346 You have both positive and negative conditions for the same thing... 
`canSpeak || !canSpeak` means "in any way". So you can just remove if/else statement because your `else` branch will never be executed.

**Comment by ghost** [comment]
i see, hold on

**Comment by ghost** [comment]
> 
> 
> @Odyssey346 You have both positive and negative conditions for the same thing...
> `canSpeak || !canSpeak` means "in any way". So you can just remove if/else statement because your `else` branch will never be executed.

ah right i'm stupid, i fixed it in the latest commit

**Pull request merged**
