### PR TITLE
DOC: Fix camelCase

### PR DESCRIPTION
**Pull request by ayushman17**
- [x] Docs have been updated (for bug fixes/features)

docs update => camelCase: Github

### Other information:
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>

### CODE REVIEW

**Comment by willdoescode** [comment]
please follow the proper pattern for commit messages _(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)_

> to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

**Review by toydotgame — APPROVED** [review]
Not necessarily camelCase, but proper capitalisation would be better. :+1:

**Comment by ayushman17** [comment]
Yeah, can you Merge it?

**Comment by willdoescode** [comment]
> please follow the proper pattern for commit messages _(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)_
> 
> > to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`
> 
> to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

@ayushman17

**Comment by willdoescode** [comment]
ill merge after you fix.

**Comment by ayushman17** [comment]
Thanks!

**Pull request merged**
