### PR TITLE
feat(kibbeh): Chat Features

### PR DESCRIPTION
**Pull request by f1shy-dev**
Hey! This PR isn't done yet, but here's the draft to-do list:

- [x] Re-add the emoji picker
- [ ] Add emoji autocomplete
- [ ] Make chat shake (like discord) when you are on a message sending cooldown
- [ ] Make emojis rendered inside the message send box (the actual emoji is shown instead of `:emojiName:`)

### CODE REVIEW

**Comment by f1shy-dev** [comment]
*Note: I probably won't split this PR into multiple PRs because the context is mostly the same in one area (chat and emojis)*

**Comment by goldyydev** [comment]
@vishy-dev I thought you were also implementing Twemoji, do you mind telling me if you aren't so I can assign it to another person?

**Comment by benawad** [comment]
this should be 4 prs

**Comment by f1shy-dev** [comment]
make that 6, (twemoji and custom emoji picker now)

**Pull request closed without merging**
