### PR TITLE
fix(MyProfilePage.tsx): fix chat box not closing when logging out

### LINKED ISSUE #1368: Logging out doesn't close the chat box.
**Describe the bug**
If you log out without actually _leaving_ the room, the chat box of the room doesn't go away

**To Reproduce**
1. Join a room.
2. Click on your profile picture to go to your profile
3. Logout
4. See the home page with the chatbox

**Expected behavior**
The chatbox shouldn't appear on the homepage.

**Screenshots**
Screen Shot 2021-03-20 at 18 05 43
Screen Shot 2021-03-20 at 18 05 52
Screen Shot 2021-03-20 at 18 06 03

**What device are you on?**
Browser: Brave 1.21.76
OS: macOS 10.13.6

**Additional context**

### PR DESCRIPTION
**Pull request by AmitGolden**
Fix #1368, chat box is now closed when logging out.

### CODE REVIEW

**Review by bansalarnav — CHANGES_REQUESTED** [review]
Can you please remove the `console.log` at line 24? Rest seems fine to me

**Comment by AmitGolden** [comment]
Oops, I put this for debugging and forgot to take it down

**Review by wes337 — APPROVED** [review]

**Review by amitojsingh366 — APPROVED** [review]

**Comment by amitojsingh366** [comment]
Is this ready to merge? Any more changes?

**Review by bansalarnav — APPROVED** [review]

**Comment by bansalarnav** [comment]
> 
> 
> Is this ready to merge? Any more changes?

seems ready to me

**Pull request merged**
