### PR TITLE
Getting rid of the false emojis.

### PR DESCRIPTION
**Pull request by theCow61**
Linus Torvalds (you probably don't know him, but he is the guy who made lunix)  has made this commit and told me to send it for him because he doesn't have time to open the pull request him self. There are too many emojis in this file from the original I made and it is getting out of hand. It was suppose to be a simple emoji but `false` emojis have corrupted it. This is why Linus has fixed this.

### CODE REVIEW

**Comment by theCow61** [comment]
Ignore the wrong profile picture on the commit author, it is Linus, github is having issues.

**Comment by TheOtterlord** [comment]
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

**Comment by willdoescode** [comment]
Wait is that linus torvalds??!??!

**Comment by TheOtterlord** [comment]
@willdoescode it's not a signed commit, so probably not

**Comment by Knoxo** [comment]
He probably use [git-blame-someone-else](https://github.com/jayphelps/git-blame-someone-else)
> Sorry for destroying the fun lol

**Comment by theCow61** [comment]
@TheOtterlord he doesn't sign his commits for non lunix related things.

**Comment by toydotgame** [comment]
Linux Torbvald?!?!?!?!?!?!!!!!!!!1

**Pull request merged**
