### PR TITLE
Added documentation for translation support

### PR DESCRIPTION
**Pull request by BronzW**

### CODE REVIEW

**Comment by amitojsingh366** [comment]
please use proper commit messages *(`yarn commit` or `yarn commit:signed`)*

**Comment by BronzW** [comment]
Can't do that when editing directly on github.

**Comment by amitojsingh366** [comment]
> Can't do that when editing directly on github.

but you need to follow it otherwise your pr won't be merged....
if you can't run the commands you can write the commit msgs yourself just make sure they follow the format, if they follow the checks should pass

**Comment by dk-raw** [comment]
@BronzW rename the commit with the proper formatting. Just found about that today

**Pull request closed without merging**
