### PR TITLE
Fixes #528 - unban from chat

### LINKED ISSUE #528: can't unban from the chat
can't unban from the chat even if your admin

### PR DESCRIPTION
**Pull request by wes337**
You can now unban users from chat. Not sure if this even works though, as I can't get Shawarma running on localhost. Kousa compiles fine though. Resolves #528

### CODE REVIEW

**Comment by goldyydev** [comment]
@Melonai Please resolve the conflicts.

**Review by jamesql — CHANGES_REQUESTED** [review]
Please revert your package-lock.json

**Comment by jamesql** [comment]
`!profile.roomPermissions?.isMod`

what is the purpose of this on the profilemodal?

**Comment by wes337** [comment]
> 
> 
> `!profile.roomPermissions?.isMod`
> 
> what is the purpose of this on the profilemodal?

Hmm, if I remember it's a check to see if you're an admin/mod so that you actually have permissions to unban a user from the chat.

**Comment by jamesql** [comment]
Would this not have the opposite effect due to the not operator?

**Comment by wes337** [comment]
> Would this not have the opposite effect due to the not operator?

Yeah. Is this worth fixing and resolving the conflicts? Or should I just close this PR and scrap this issue?

**Comment by benawad** [comment]
manually merged/migrated

**Pull request closed without merging**
