### PR TITLE
update Chinese translation

### PR DESCRIPTION
**Pull request by xuhangc**

### CODE REVIEW

**Comment by ermalsh** [comment]
Resolve conflicts, otherwise looks good to me.

**Review by HarrisonMayotte — APPROVED** [review]
Conflicts resolved. Looks good to me.

**Comment by ermalsh** [comment]
@HarrisonMayotte this should not have been merged, please validate the JSON before merging these.

**Comment by HarrisonMayotte** [comment]
I've gone ahead and reverted that @ermalsh and am reopening this one.
Edit: It doesn't appear that I can re-open this one, but @xuhangc if you could open a new PR and fix the JSON syntax that can be re-reviewed.

**Pull request merged**
