### PR TITLE
Created MobileNav Component

### PR DESCRIPTION
**Pull request by bansalarnav**
Created MobileNav component (https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2440)

### CODE REVIEW

**Review by goldyydev — APPROVED** [review]
Seems alright to me 👍

**Review by HarrisonMayotte — APPROVED** [review]
All good to me.

**Review by ajmnz — CHANGES_REQUESTED** [review]
~~Mobile-only components should be put under `ui/mobile`, as stated in the issue.~~

All the icons are already available under `src/icons`. Some of them will need to be `20px` wide/tall (check on Figma), so you can pass `width={20} height={20}` as props to the icon component for it to scale to the desired size.

**Review by ajmnz — CHANGES_REQUESTED** [review]
~~The existing `SmSolidPlus` needs to be left as is, because it's being used by `UpcomingRoomsCard`. You'll need to put the new plus icon under `icons/mobile` and `svgr` it.~~

**Review by HarrisonMayotte — APPROVED** [review]
Looks good to me.

**Comment by HarrisonMayotte** [comment]
Not what I meant to do 😂. Just looking for a second review from @ajmnz

**Review by ajmnz — CHANGES_REQUESTED** [review]
Pull latest from `staging`. Some of your icons aren't updated

**Comment by goldyydev** [comment]
Can you please update the Storybook so it would work by default?

**Comment by bansalarnav** [comment]
Closing this due to some problem with commits. Creating a new one (#1382 )

**Pull request closed without merging**
