### PR TITLE
Update .prettierrc.js

### PR DESCRIPTION
**Pull request by HonbraDev**
feat(global): improved linting.

### CODE REVIEW

**Comment by HoloPanio** [comment]
Now hold on guys, We should really reconsider this before we just close it...

**Comment by HoloPanio** [comment]
Now hold on guys, We should really reconsider this before we just close it...

**Comment by HoloPanio** [comment]
Now hold on guys, We should really reconsider this before we just close it...

**Comment by HoloPanio** [comment]
Now hold on guys, We should really reconsider this before we just close it...

**Comment by HoloPanio** [comment]
Now hold on guys, We should really reconsider this before we just close it...

**Comment by amitojsingh366** [comment]
lol wtf

**Comment by HoloPanio** [comment]
This is now on my hands to decide if these changes are necessary

**Review by HoloPanio — COMMENTED** [review]
Much bad

**Comment by HoloPanio** [comment]
Now common guys, this won't be really helpful

**Comment by HoloPanio** [comment]
I promise to keep this pr closed FOREVER!!!

**Comment by HoloPanio** [comment]
This **MUSTN'T** go to production!

**Comment by HoloPanio** [comment]
Тиа **ДОЛЖНА** перейти в производство

**Comment by HoloPanio** [comment]
1

**Comment by HonbraDev** [comment]
2

**Comment by Odyssey346** [comment]
HELLO

**Comment by HoloPanio** [comment]
3

**Comment by ajmnz** [comment]
I'm done, @TheOtterlord this is on your hands now

**Comment by amitojsingh366** [comment]
ok, can we please be civil and stop this now. this is getting out of hand

**Comment by HoloPanio** [comment]
Big Sad =(

**Pull request closed without merging**
