### PR TITLE
add custom emoji

### PR DESCRIPTION
**Pull request by rishitxyz**
Added a  custom thugpepe emoji with size 28 x 28 with the required data in `Emotedata.ts`.

### CODE REVIEW

**Comment by vi241** [comment]
pls resolve conflicts

**Comment by ofsho** [comment]
I will fix it

**Comment by rishitxyz** [comment]
> I will fix it

Thanks I cannot find the conflict can you help me please?

**Comment by vi241** [comment]
no

**Comment by vi241** [comment]
you have a problem

**Comment by vi241** [comment]
add the { to the CryptoBTC

**Comment by rishitxyz** [comment]
Yeah I did that

**Comment by rishitxyz** [comment]
Is it fixed now?

**Comment by vi241** [comment]
yes

**Comment by rishitxyz** [comment]
Okay!

**Pull request merged**
