### PR TITLE
Added package-lock.json to .gitignore

### PR DESCRIPTION
**Pull request by willdoescode**
No reason to have it on github

### CODE REVIEW

**Comment by aidenybai** [comment]
Technically there is a point to have it on github, it ensures that the dependencies of the dependencies (and so on) are locked. However, this probably isn't super important

**Comment by willdoescode** [comment]
Having the package-lock.json on github helps with addition farming as one new dependency or change can mean a lot of changes in package-lock.json

**Comment by willdoescode** [comment]
removing it once and for all can fix this

**Comment by nadirabbas** [comment]
but we still need the lockfile on GitHub. There can sometimes be breaking changes in newer versions.

**Comment by benawad** [comment]
i want lockfile

**Pull request closed without merging**
