### PR TITLE
fix(kibbeh): Update Dutch Translations

### PR DESCRIPTION
**Pull request by niels-bosman**
Updated Dutch translations and edited some that are inconsistent / formatted weirdly.

### CODE REVIEW

**Comment by amitojsingh366** [comment]
please use proper commit messages *(`yarn commit` or `yarn commit:signed`)*

**Comment by samarmohan** [comment]
We can't merge until all checks pass, please run `git commit --amend -m "fix(kibbeh): Update dutch translations "`. You need the type, scope, and message. Only the first word of the sentence can be capitalized.

**Comment by niels-bosman** [comment]
I cant commit again and uncommit.. Any help or should I open new PR?

**Comment by amitojsingh366** [comment]
> 
> 
> I cant commit again and uncommit.. Any help or should I open new PR?

follow this https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages

**Comment by dk-raw** [comment]
@niels-bosman are you going to fox it?

**Comment by niels-bosman** [comment]
yes ill fix it tomorrow

**Comment by dk-raw** [comment]
🦊

**Review by jobveldhuis — APPROVED** [review]
Regardless of commit message issues, changes to the translations look good to me.

**Pull request closed without merging**
