### PR TITLE
Malawach - a shawarma rewritten in go

### PR DESCRIPTION
**Pull request by shmuelhizmi**
benchmarks -
image
I connected 52 browsers to the server and the server still only shows around 0 percent of CPU usage and almost no ram usage.

server info
CPU - Intel i5-6500 (4) @ 3.600GHz
RAM - 23946MiB

### CODE REVIEW

**Comment by DGKSK8LIFE** [comment]
I really love the idea and increased performance but I doubt Ben will approve it.

**Comment by benawad** [comment]
If they both use the same mediasoup C++ engine, where does the performance come from?

**Comment by benawad** [comment]
If we want to rewrite the voice server, another option is https://www.membraneframework.org/

**Comment by willdoescode** [comment]
Go could probably add a small performance boost but this is pretty extreme, we are talking about changing the HYPEBEAST stack here

**Comment by DGKSK8LIFE** [comment]
> Go could probably add a small performance boost but this is pretty extreme, we are talking about changing the HYPEBEAST stack here

Yeah but if a change to said HYPEBEAST stack saves lots of money, makes the application run faster, etc, it's justified IMO. You can just change the definition of hypebeast stack to include all tech. Fuck it, php .NET hype stack

**Review by willdoescode — CHANGES_REQUESTED** [review]
make HYPEBEAST stack complient.

**Comment by htmldev29** [comment]
When in the course of human events it becomes necessary for one people to dissolve the political bands which have connected them with another and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation. 

BEN DOESN'T WANNA MERGE THIS :(

**Comment by ghost** [comment]
Bro this not work they dont belive.. In the future i cant continue Enviado desde mi HUAWEI P20-------- Mensaje original --------De: Louis <notifications@github.com>Fecha: lun., 1 de marzo de 2021 1:59 p. m.Para: benawad/dogehouse <dogehouse@noreply.github.com>CC: Subscribed <subscribed@noreply.github.com>Asunto: Re: [benawad/dogehouse] Malawach - a shawarma rewritten in go for much better performance (#530)
When in the course of human events it becomes necessary for one people to dissolve the political bands which have connected them with another and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.
BEN DOESN'T WANNA MERGE THIS :(

**Comment by matt-mekha** [comment]
I think this still isn't optimal performance. Maybe we should rewrite the server with [this faster alternative](https://www.youtube.com/watch?v=7d7-etf-wNI).

**Comment by willdoescode** [comment]
Cobol is not HYPEBEAST stack complient. 😔

**Comment by matt-mekha** [comment]
> Cobol is not HYPEBEAST stack complient. 😔

Ah my bad... I was thinking about the supersonic stack.

**Comment by shmuelhizmi** [comment]
@benawad  lol, you're right. I didn't think this through.
I think besides using less memory go doesn't provide much difference.

**Comment by willdoescode** [comment]
https://dogehouse.tv/room/c141e3f5-2f03-4cf6-9c70-785c1c650f91

**Comment by willdoescode** [comment]
https://dogehouse.tv/room/c141e3f5-2f03-4cf6-9c70-785c1c650f91

**Comment by hajarrashidi** [comment]
@shmuelhizmi  https://dogehouse.tv/room/c141e3f5-2f03-4cf6-9c70-785c1c650f91

**Comment by willdoescode** [comment]
@shmuelhizmi https://dogehouse.tv/room/c141e3f5-2f03-4cf6-9c70-785c1c650f91

**Comment by htmldev29** [comment]
> @benawad lol, you're right. I didn't think this through.
> I think besides using less memory go doesn't provide much difference.

Come meet with the Counsel of Doge
https://dogehouse.tv/room/c141e3f5-2f03-4cf6-9c70-785c1c650f91

**Pull request closed without merging**
