### PR TITLE
feat(kibbeh): add PWA support

### LINKED ISSUE #2150: Add a PWA support
**Is your feature request related to a problem? Please describe.**
It could be simplier (1 click to doge) and prettier (no link bar at the top) to use dogehouse as a PWA on mobile/desktop. 

**Describe the solution you'd like**
I want to be able to add PWA to my mobile/desktop from browser just like on twitter

**Describe alternatives you've considered**
Or you could create React Native WebView app and then build it to use dogehouse from mobile

### PR DESCRIPTION
**Pull request by ghost**
This fixes #2150. Works on my machine, but it definitely could be fixed. First time doing this :D should run fine tho, works absolutely fine here

### CODE REVIEW

**Comment by ghost** [comment]
okay, i noticed it has pushed some map stuff, i'll fix

**Comment by benawad** [comment]
Can we add a manifest to add app icon to homepage without PWA? I don't want a service worker.

**Comment by ghost** [comment]
I think so, but apparently that makes it not installable. Let me test it again

**Comment by ghost** [comment]
image
yeah i think we'll need a service worker. sucks

**Comment by benawad** [comment]
that's fine, I don't care about installing just app shortcut

**Comment by ghost** [comment]
lmao sorry i think i read something wrong

**Comment by ghost** [comment]
Yeah, you can install to homescreen on Android without PWA, if that's what you're asking. If it is, lemme know, I'll push my changes

**Comment by ghost** [comment]
I don't have an iPhone to test if you can do this through Safari, so you'll have to test that yourself

**Comment by benawad** [comment]
yeah I don't want service worker pwa part, but I'll take the manifest

**Comment by ghost** [comment]
done

**Pull request merged**
