### PR TITLE
added new emoji with complete info in EmoteData.ts

### PR DESCRIPTION
**Pull request by siemen-subbaiah**

### CODE REVIEW

**Comment by vi241** [comment]
itn't it tron?

**Comment by siemen-subbaiah** [comment]
Oh. My bad a typo 🤦‍♂️

**Comment by vi241** [comment]
please fix the typo and resolve conflicts

**Comment by vi241** [comment]
all you need is to resolve the conflicts

**Comment by siemen-subbaiah** [comment]
yup,done!

**Comment by vi241** [comment]
ok

**Pull request merged**
