### PR TITLE
Fix code block message

### PR DESCRIPTION
**Pull request by maskeynihal**
Only `backticks` were not being able to send. Fix code block message to handle all the possibles. 
- Allow 2 backticks as a plain text as ``

### CODE REVIEW

**Comment by maskeynihal** [comment]
cc @nadirabbas

**Comment by maskeynihal** [comment]
image

**Comment by nadirabbas** [comment]
this has been fixed already

**Comment by maskeynihal** [comment]
closes #1077 

@nadirabbas there are still some issues.

**Comment by nadirabbas** [comment]
@maskeynihal thats because changes have not been deployed. all of the points in #1077 were fixed.

**Comment by nadirabbas** [comment]
may be one of the issue still persists 😅, so I'll merge this.

**Pull request merged**
