### PR TITLE
Keep screen awake if the user is unmuted

### LINKED ISSUE #133: Keep screen on while beeing a speaker
It would be great to let the screen on as long as you want to talk. If you are just a listener it doesnt matter, but as a speaker you need to change some setting or mute yourself and then the screen turns off.

### PR DESCRIPTION
**Pull request by sahilmob**
This commit is to implement screen lock api and its polyfill to keep the screen awake if the user is speaker or specifically unmuted.

Issue #133

### CODE REVIEW

**Comment by amitojsingh366** [comment]
@sahilmob please see #1462

**Comment by sahilmob** [comment]
@amitojsingh366 I thought that this enhancement could be merged because there isn't any changes to UI components. Anyway, I will wait until new design is complete. 

Thanks

**Comment by HarrisonMayotte** [comment]
It still is classified as a feature even if it isn't a UI feature.

**Comment by sahilmob** [comment]
@HarrisonMayotte Yeah, that's right. I will until the new design is complete.

**Comment by samarmohan** [comment]
This is a dupe of #133

**Comment by overlisted** [comment]
> This is a dupe of #133

this is a PR

**Comment by nadirabbas** [comment]
12 commits?!

**Comment by sahilmob** [comment]
I don't know why the commits got mixed up with a previously merged ones.

**Comment by overlisted** [comment]
That's because you have to start a new branch for every new PR

**Comment by sahilmob** [comment]
@overlisted It happened to me again, and this time I'm sure that I have started a new branch from staging.
  
pr

**Comment by overlisted** [comment]
That's really strange. I don't know how to help you.

**Comment by sahilmob** [comment]
I will keep this for reference. The solution is to rebase the patch branch on staging. I did it to my new PR and will do it for this one later today.
[reference](https://stackoverflow.com/a/45286781/10521942)

**Comment by overlisted** [comment]
don't use npm in kibbeh

**Review by overlisted — CHANGES_REQUESTED** [review]
don't use npm in kibbeh

**Comment by sahilmob** [comment]
@overlisted I'm sorry. I I didn't get that!.

**Comment by amitojsingh366** [comment]
> 
> 
> @overlisted I'm sorry. I I didn't get that!.

Did you mean to say you did not understand what @overlisted ment or did you mean to say that it was a mistake?
If it was the first case and you didn't understand what @overlisted ment then ill make it more clear
@overlisted ment to say that we are not using `npm` in kibbeh anymore and please use `yarn` instead of `npm`.
You can do that by reverting `package-lock.json` and then running `yarn install` in the kibbeh directory

**Comment by sahilmob** [comment]
It was the first one. Thanks

**Comment by amitojsingh366** [comment]
> 
> 
> It was the first one. Thanks

Also keep in mind both kibbeh and kofta now use yarn v2

**Comment by sahilmob** [comment]
Duly noted. Thanks

**Comment by sahilmob** [comment]
@amitojsingh366 Actually changes in this PR are in `kofta` not `kibbeh` which seems to be not included in the workspace, therefore, when I run `yarn install` I get the following error:

> Usage Error: The nearest package directory (./dogehouse/kofta) doesn't seem to be part of the project declared in ./dogehouse.
>- If the project directory is right, it might be that you forgot to list kofta as a workspace.
>- If it isn't, it's likely because you have a yarn.lock or package.json file there, confusing the project root detection.
>
>$ yarn run [--inspect] [--inspect-brk] <scriptName> ...

yarn

**Review by overlisted — APPROVED** [review]
looks good

**Comment by BronzW** [comment]
Anything stopping this from being merged?

**Comment by benawad** [comment]
this got manually merged

**Pull request closed without merging**
